### ISSUE TITLE
For better scalability - seperate "pages" into a files folder and retain critical data in database.js

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#100]
1. Each page could be it's own text file to open possibilities of WonderCMS being used as a blog.
2. Critical data such as default homepage, login URL, password, menu items, db version, main website title and chosen theme should be kept in database.js.

@NicolasCARPI, since you are currently the most active contributor and have the almighty knowledge of all PHP related issues :) how would one go about solving this properly?

I still have an old WonderCMS version 0.4.1 lying around that worked without a database.js and saved each file separately into text files, but it had other issues since it included the password file, login URL and other critical data files.

[wondercms-0.4.1.zip](https://github.com/robiso/wondercms/files/2848902/wondercms-0.4.1.zip)

**Comment by NicolasCARPi** [comment]
I think it's a bit weird to talk about scalability for this project. If one wants something "scalable", meaning with at least hundred pages, wcms might not be the best choice anyway. Something with a RDBMS (MySQL, Postgres) will be much better.

Also, there are **countless** static blog generator out there (see [https://www.staticgen.com/](https://www.staticgen.com/)), and they are doing a great job at that.

Going in this direction seems like a bad decision imho. Wcms is good for making a website with a few pages and some content, it's easy to edit it, and to install it. Having a blog like function from static pages is out of the scope of this project. It might be something that can be added, sure, but not with the current codebase, or it'll just be a big mess. 

I thought you wanted to keep things simple, where does this feature request come from? Also, at which point does the database.js is causing an issue? I'm sure one would need to have maybe thousand pages before the file grows too big and make things slow.

**Comment by robiso** [comment]
After reading your well written input, I agree with you.

To answer where this came from, I've been following two bloggers that tried out WonderCMS and were "afraid" that it would immediately slow down their sites if they were to make a couple dozen blogs. For the fun of it, I'll create a 1000 pages and try running a couple of speed tests to see where the possible bottleneck is (but this could be highly varied from different servers and server connections, so it might be futile (but fun to see nonetheless)).

And thanks for helping me decide and think this through, it makes way more sense after a healthy discussion.

Closing issue and thanks for you input Nicolas!
