### ISSUE TITLE
Correct Cross Site Scripting [REOPENED]

### ISSUE THREAD

**Issue by hypnito** [robiso/wondercms#11]
The file editinplace.php do not sanitize all the request and it is possible to execute a Cross-Site Scripting XSS attacks.

/wonder/js/editinplace.php?page=<script>alert(1)</script>

In the code, line 39, echo $_GET["page"];

https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

When you fix the bug, please, can you include my name in the release notes when the bug will be corrected? Manuel Garcia Cardenas advidsec@gmail.com

Regards,

**Comment by robiso** [comment]
You must have seen an old report on the old version, this doesn't work on the latest 0.9.8 which was released numerous days ago.
You can test this here: https://wondercms.com/demo/js/editInplace.php?page=<script>alert(1)</script>

**Comment by hypnito** [comment]
Hi,

I am trying with 0.9.8 :)

![image](https://cloud.githubusercontent.com/assets/23498371/20461663/d6ccd702-af04-11e6-96f1-d12c2b7d277b.png)

**Comment by hypnito** [comment]
And yes, your Demo Web is vulnerable (test it on firefox)

![image](https://cloud.githubusercontent.com/assets/23498371/20461670/236a242a-af05-11e6-80c3-bd7b5d850265.png)

**Comment by robiso** [comment]
Can someone confirm this, I've been re-trying to do this on Firefox + Chrome (Ubuntu) and can't seem to get this to show.

Re-opening issue.  Thank you hypnito, if there's any way you can push a fix, I'll see that you're added to the special contributors list. Re-testing this.

**Comment by hypnito** [comment]
Patched, can you verify please?

________________________________
De: robiso <notifications@github.com>
Enviado: domingo, 20 de noviembre de 2016 13:51:39
Para: robiso/wondercms
Cc: hypnito; Author
Asunto: Re: [robiso/wondercms] Correct Cross Site Scripting [REOPENED] (#11)


Can someone confirm this, I've been re-trying to do this on Firefox + Chrome (Ubuntu) and can't seem to get this to show.

Re-opening issue. Thank you hypnito, if there's any way you can push a fix, I'll see that you're added to the special contributors list. Re-testing this.

-

**Comment by robiso** [comment]
Verified and tested on a Windows machine, everything seems to be working fine. Hypnito, thank you once again, your signature will be publicly posted on the special contributors page + release note.

**Comment by hypnito** [comment]
It is my pleasure ! maybe it is possible notify when release the new version? [😊]  and link to the contributors+release notes!


Thanks!

________________________________
De: robiso <notifications@github.com>
Enviado: domingo, 20 de noviembre de 2016 19:57:15
Para: robiso/wondercms
Cc: hypnito; Author
Asunto: Re: [robiso/wondercms] Correct Cross Site Scripting [REOPENED] (#11)


Verified and tested on a Windows machine, everything seems to be working fine. Hypnito, thank you once again, your signature will be publicly posted on the special contributors page + release note.

**Comment by robiso** [comment]
New version updated: https://wondercms.com

Both you and Yassine are mentioned at:
https://wondercms.com/special-contributors - if you have a website, we can link to it from your name
https://wondercms.com/forum/viewtopic.php?f=8&t=761
http://www.opensourcecms.com/scripts/details.php?scriptid=719&name=WonderCMS

Great job and thank you once again, love quick actions like this.
