### ISSUE TITLE
Create theme and plugin screenshots

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#114]
And add them to https://wondercms.com/themes and https://wondercms.com/plugins.

**Comment by robiso** [comment]
@NicolasCARPi, @notcarbide
Finished the theme and plugin screenshots, any feedback is appreciated.
- https://www.wondercms.com/approved-themes
- https://www.wondercms.com/approved-plugins

**Comment by NicolasCARPi** [comment]
Much, much better! :clap: 

I would rename "2018 default" in "Default" (or "A name" (default)), and give a name to "2016 default" ;)

my 2 cents.

**Comment by notcarbide** [comment]
Looks good.
The naming I feel is a bit nitpicking, but at the same time, creating a sort of brand for the WonderCMS themes vs. regular themes would only help them stand out, while at the same time put their name on par with other named themes.
Even if you went with a basic naming convention (a previous project I worked on, went with ice cream flavors), this way original names are easy to come up with, but they also have a special WonderCMS "flavor" to them. Of course you could always tag older default versions with something like the year they became default. (i.e. 2018 default -> Soft Mint (default); 2016 default -> Legacy Vanilla (2016)) just as an example.

**Comment by robiso** [comment]
@NicolasCARPi, @notcarbide 
feedback appreciated! Renamed both themes and really like it. Kudos guys!

> Even if you went with a basic naming convention (a previous project I worked on, went with ice cream flavors), this way original names are easy to come up with, but they also have a special WonderCMS "flavor" to them.

Awesome suggestion! Would you guys prefer ice cream themed names, or something like musicians/music type? We could also go with planets, stars.

I'm voting for the ice cream themed names (until I can figure out something better, or see a better suggestion): Thanks @notcarbide!

**Comment by notcarbide** [comment]
The only issue with ice cream names is the name might be seen as implying color (strawberry - pink, etc.). Although with your idea of musicians, the name Stevie immediately popped into my head and I got this idea. Maybe name them after all things "Wonder" ("Stevie" for Stevie Wonder, WonderWomans real name, people/things that might relate to the wonders of the world [or their names themselves] etc).

**Comment by NicolasCARPi** [comment]
I like the idea of wonder related names, but it should be subtile imho:

"Stevie" is good
instead of wonderwoman -> "Gal"
"Alice" for alice in wonderland
"Bar" for wunderbar (german word)
"Oasis" for wonderwall (song)
"Fest" for wonderfest (festival)
"Wanda" for a fish called wanda (movie)

:D 

And I agree that a theme with "mint" in the name has to be green! And vanilla would be black and white…

**Comment by robiso** [comment]
@notcarbide and @NicolasCARPi, thanks for the awesome suggestions. Looks like "wonderful" times are ahead.

> And I agree that a theme with "mint" in the name has to be green! And vanilla would be black and white…

Isn't this already the case (at least pretty close with the colors)? The two examples below:
<img width="1010" alt="mint-and-vanilla" src="https://user-images.githubusercontent.com/6200139/54489853-14fc4880-48b1-11e9-9f56-3925b59d48b7.png">

Name suggestions as could be implemented in the near future.
- Black -> **Carbon**
- Dark blue **Catmint**
- Gold -> **Bar**
- Green -> **Fest**
- Light blue -> **Oasis**
- Pink -> **Rosa**
- Purple -> **Gal'**
- Red -> **Ruby Gemstone**
