### ISSUE TITLE
[dev] Commit 6dad1b2 modifies minified css

### ISSUE THREAD

**Issue by notcarbide** [robiso/wondercms#128]
Commit 6dad1b2f9e528aa3e58e119c12df6eaa5bc04fa4 on dev branch modifies minified css.

Upon building, grunt overwrites this file so the changes are not persistent.

Recommend these changes be made to the relevant `src/css/*` file and `assets` be added to `.gitignore`

**Comment by NicolasCARPi** [comment]
Yep, minified file should be in .gitignore. They'll come with the built zip.

**Comment by notcarbide** [comment]
Would it be a good idea to minify summernote `admin.*` files into the minified admin files in `assets` via Gruntfile? I've tried it locally and it works fine, while reducing size by ~2kb, although I'm not sure if this is the best practice for it, since summernote IS a plugin (although it is included by default). Dunno how modular we're trying to be with it (for removal purposes specifically) or if it's worth it.

**Comment by robiso** [comment]
@NicolasCARPi @notcarbide, would the correct procedure as this stage be the following?
1. Update the non minified CSS files with latest changes?
2. Add the minified files to the .gitingore?
3. Should the data folder also be added to .gitignore?

> Would it be a good idea to minify summernote admin.* files into the minified admin files in assets via Gruntfile? I've tried it locally and it works fine, while reducing size by ~2kb, although I'm not sure if this is the best practice for it, since summernote IS a plugin (although it is included by default). Dunno how modular we're trying to be with it (for removal purposes specifically) or if it's worth it.

I would avoid this for now as there's always an option for including this in the future version(s).

**Comment by notcarbide** [comment]
> 1. Update the non minified CSS files with latest changes?
> 2. Add the minified files to the .gitingore?
> 3. Should the data folder also be added to .gitignore?

Yup! But after some thought adding minified files to gitignore would make the build step a requirement. What could also be done is to add a readme to the directory generated files are in, declaring that the files are automatically generated and to edit the source files and update them based on the build step. Or something similar, kinda like the way Linux has a boilerplate for auto generated headers.

As for adding data, it is up to you. The only real reason I could see for it to be added, is if someone were to develop on an already deployed instance (where data has already been generated).

**Comment by NicolasCARPi** [comment]
Yes, minified files and data folder should be gitignored.

**Comment by robiso** [comment]
Currently we have:
```
database.js
data
files
plugins
node_modules
vendor
```

I believe the plugins should not be gitignored since we'll include summernote by default and also the assets folder should be added. Is it enough to gitignore the whole data and assets folder instead of including each file (such as database.js from the data folder)?

Would the suggested .gitignore suffice?
```
assets/*
data/*
node_modules/*
vendor/*
```

**Comment by NicolasCARPi** [comment]
> Would the suggested .gitignore suffice?

LGTM

**Comment by robiso** [comment]
Closing issue, thanks @NicolasCARPi and @notcarbide.
