### ISSUE TITLE
[dev-3.0.0] Update all plugins to work with upcoming WCMS version 3.0.0 - Done

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#131]
All plugins have been updated to work with the future WonderCMS 3.0.0 version:
https://github.com/robiso/wondercms-plugins/tree/dev-3.0.0-plugins/plugins

**1. One of the plugins (additional contents) has an issue, the additional contents can't be deleted.**
- The issue seems to be on lines [67](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L67), [69](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L69), [71](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L71), [79](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L79) and [83](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L83), where the db fetch and the unset occurs.

Minor notes:
1. The Summernote plugin includes the fix from @notcarbride.
2. The contact form plugin got an upgrade with a config file, making it easier to setup. Thanks to @Jeremy1980. I also added some bootstrap styling and fixed a couple of issues (like double email sending).

**Comment by robiso** [comment]
@NicolasCARPi, there still seems to be an issue when deleting a certain additional editable area (when there are multiple editable areas).

In the following scenario (where there are two additional content fields on one page), deleting the "Test 2" also deletes the "Test 1" field:
<img width="1150" alt="deleting-editable-fields" src="https://user-images.githubusercontent.com/6200139/56470258-a036a400-6444-11e9-883c-19a117a6ca73.png">

However, when deleting the bottom one first, it works as expected.

**Comment by NicolasCARPi** [comment]
Yes I can reproduce. I'll look into it.

**Comment by NicolasCARPi** [comment]
I looked into it, and I must say my head is hurting. The code is incredibly complicated and hard to read/understand. Things could be soooo much shorter and cleaner. I get to the point where only the correct additional content is deleted in the db, but the others disappear, and reappear when user clicks the + button… (!!)

The code in the plugin for the delete action can be reduced to:

~~~php
    if ($Wcms->loggedIn) {
        if (isset($_POST['delac'])) {
            $contentId = (int) mb_substr($_POST['delac'], -1);
            if (getContentV2('addition_content_' . $contentId)!=false) {
                $key = 'addition_content_'.$contentId;
                $Wcms->unset($target, $page, $key);
                $key = 'addition_content_show_'.$contentId;
                $Wcms->unset($target, $page, $key);
~~~

I have yet to understand what the [for loop](https://github.com/robiso/wondercms-plugins/blob/dev-3.0.0-plugins/plugins/addition_contents/addition_contents.php#L71-L85) below is for… AFAIK we're only deleting one block at the time, so why a for loop?? (with weird parameters that produce infinite loop too!!!)

As I said by email, working on such codebase is like reverse engineering closed source software… Or software written by a madman :p

**Comment by robiso** [comment]
@NicolasCARPi, aren't we all mad men or not far from it? :)
Luckily, I didn't write this. But if I did, it would probably be even crazier.

Not sure why it doesn't work with the v3.0.0, it works normally with the 2.7.0 and previous versions (as can be checked in the demo: https://www.wondercms.com/demo/)

**Comment by notcarbide** [comment]
Would [array_splice()](https://php.net/manual/en/function.array-splice.php) work better than unset() for this sorta thing?

**Comment by notcarbide** [comment]
I genuinely don't understand how this even worked before?
From what I can tell, deleting `additional_content` that isn't last should break [this loop](https://github.com/robiso/wondercms-plugins/blob/74822b97030216c0b035a203505370f61916cbfc/plugins/addition_contents/addition_contents.php#L154) early.
When testing with @NicolasCARPi's example (which removes the right db entry), the block would only ever show if all the ascending numbers were available as db entries.

So something like this in db will show all blocks (NOTE: even when out of order in db like this, blocks are shown in numeric order in browser[content_1, content_2, etc...])
```
            "addition_content_1": "Empty content",
            "addition_content_show_1": "hide",
            "addition_content_3": "Empty content",
            "addition_content_show_3": "hide",
            "addition_content_4": "Empty content",
            "addition_content_show_4": "hide",
            "addition_content_2": "Empty content",
            "addition_content_show_2": "hide"
```
Remove the third block, and `content*_4` doesn't show
```
            "addition_content_1": "Empty content",
            "addition_content_show_1": "hide",
            "addition_content_4": "Empty content",
            "addition_content_show_4": "hide",
            "addition_content_2": "Empty content",
            "addition_content_show_2": "hide"
```
When adding after this, `content*_3` is the new block and the block mentioned above is visible again
```
            "addition_content_1": "Empty content",
            "addition_content_show_1": "hide",
            "addition_content_4": "Empty content",
            "addition_content_show_4": "hide",
            "addition_content_2": "Empty content",
            "addition_content_show_2": "hide"
            "addition_content_3": "Empty content",
            "addition_content_show_3": "hide",
```

**Comment by robiso** [comment]
I'm not entirely sure. I might have missed something when converting this plugin to work with v3.0.0. I'll try converting it from scratch again.

On another note, I'll get another PHP dev to take a look at this in the upcoming weeks. Hopefully we can figure something out.

@notcarbide, would you mind giving the 3.0.0 experimental branch a run? https://github.com/robiso/wondercms/tree/experimental3.0.0
It includes some other minor fixes and upgrades. It also removes the necessity for separating wcms into multiple files (and keeps the "unorthodox" single file structure like we've had for the past good 10 years). Also no build steps are required.
This will also make updating the main index.php file easier again.

**Comment by notcarbide** [comment]
@robiso the deleting issue with "additional_contents" still exists unfortunately.

Also I've noticed with 3.0 (both dev and experimental), I have issues accessing files uploaded via WonderCMS.

**Comment by robiso** [comment]
@notcarbide, still haven't gotten to converting it from scratch.

That's pretty weird, I can't seem to reproduce the 403 with uploaded files. Does this happen in any specific cases or just uploading through the file uploader and trying to fetch the files?

Can you post a few specs on the server you're running? (Apache, PHP version)
Also, are you running it in the root directory (that's the only case I haven't tested yet).

Thanks for testing, will make sure you get the honorable mention after 3.0.0 is released, also you've been plated gold on the contributors page (https://www.wondercms.com/special-contributors).

**Comment by robiso** [comment]
@notcarbide, updated the latest experimental branch and tried changing permissions for those folders to 755 (from 700).

Give it a clean install and let me know if it persists.

**Comment by notcarbide** [comment]
> @notcarbide, updated the latest experimental branch and tried changing permissions for those folders to 755 (from 700).
> 
> Give it a clean install and let me know if accessing the files works as expected.

Ugh last 2 weeks just zoomed by sorry for the delayed response but this fixed it.

**Comment by robiso** [comment]
@notcarbide, no problem at all.

The only issue that we have at the moment is the additional contents plugin. Will try to resolve it in the upcoming weeks.

Thanks for all the testing and confirming. 🎉

**Comment by robiso** [comment]
@NicolasCARPi and @notcarbide, happy to announce this was fixed. The additional contents plugin now correctly removes the additionally created field.

https://github.com/robiso/wondercms-plugins/commit/85c946b9cd28706a655611c8a216cdea0eb2e594

Thanks and kudos to @slavenstancic for figuring this out! 🏆
