### ISSUE TITLE
[dev-3.0.0] Open issues/bugs for future version

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#134]
<del>**1. When using the "UP" and "DOWN" arrows to move menu items (bug):**</del>
- <del>Example: If there are two menu items "Home" and "Example", and the user tries to move the "Example" page "UP", both menu items become "Example".---</del>

**<del>2. Plugin deleting issues:**
- <del>When deleting a plugin that has an ".htaccess" file inside the folder (like hits-counter does), the directory doesn't get fully deleted.</del>
- <del>When there is a directory present (for example "test") and an additional file ("test.zip"), both of these files get deleted.</del>

**3. Implementing a 1 click update functionality:**
- Similarly to the 2.6.0 version, enable the user to overwrite system files from the latest master branch on GitHub if their WonderCMS version is older than the version on GitHub.

**Comment by notcarbide** [comment]
@robiso @NicolasCARPi I was able to fix the second on the list, but from what I've read `GLOB_BRACE` probably isn't the best way of doing this:
```
diff --git a/src/classes/Wcms.php b/src/classes/Wcms.php
index 3b1b531..a32f6b5 100644
--- a/src/classes/Wcms.php
+++ b/src/classes/Wcms.php
@@ -873,7 +873,7 @@ EOT;
     private function recursiveDelete(string $file): void
     {
         if (is_dir($file)) {
-            $list = glob($file . '*', GLOB_MARK);
+            $list = glob($file . '/{,.}[!.,!..]*', GLOB_BRACE);
             foreach ($list as $dir) {
                 $this->recursiveDelete($dir);
             }
```
I tried a few things to get something similar working without `GLOB_BRACE` but I know virtually nothing about php lol

**Comment by NicolasCARPi** [comment]
@notcarbide I'm planning to work on that too, and use [directoryIterator](https://www.php.net/manual/en/class.directoryiterator.php). But thanks for trying anyway :)

**Comment by robiso** [comment]
@notcarbide, I actually played around with the GLOB_BRACE but managed to always mess something up. Thanks! 🍺

@NicolasCARPi, I think this is an acceptable solution and would ask you to postpone any work on that feature (will include @notcarbide's fix for now).

**Comment by notcarbide** [comment]
I mainly questioned the use of GLOB_BRACE because of things like this: 
https://stackoverflow.com/questions/2536924/glob-brace-portability
Also doesn't really help readability with all the jargon required to get glob to work properly.

So even though using the iterator would be more nontrivial than what I have posted, would it be a cleaner solution that also solves the caveats of using glob? I feel like some of those helpers would def help readability. Or is it acceptable for another reason?

**Comment by NicolasCARPi** [comment]
We don't really care about Solaris honestly.

**Comment by notcarbide** [comment]
I didn't think so, and although it's not just Solaris, I'm sure the same sentiment stands for the systems that don't support it. I was just questioning which solution the most optimal. Never learn if you never ask :)

**Comment by NicolasCARPi** [comment]
IMHO using standard classes or symfony components is the best, because it deals with edge cases. But I think what @robiso is saying is that it's good enough for now.

**Comment by robiso** [comment]
@notcarbide, as @NicolasCARPi hinted, a solution with DirectoryIterator is also possible. I tried playing around with it and got the following working:
```
    private function recursiveDelete($file): void
    {
        if (is_file($file)) {
            unlink($file);
        } elseif (is_dir($file)) {
            $files = new \DirectoryIterator($file);
            foreach ($files as $dirFile) {
                if (!$dirFile->isDot()) {
                    $dirFile->isDir() ? $this->recursiveDelete($dirFile->getPathname()) : unlink($dirFile->getPathname());
                }
            }
            rmdir($file);
        }
    }
```

The above also checks if the user possibly has a .ZIP file and deletes it (I had a couple of cases like this myself, where I had also had a ZIP file, which isn't really a directory.

I haven't read about the glob caveats, but if you guys think the above is better, let's go with it.

**Comment by notcarbide** [comment]
> The above also checks if the user possibly has an actual .ZIP "file" and deletes it (I had a couple of cases like this myself, where I had also had a ZIP file, which isn't really a directory).

Tested and looks good to me :) Gets rid of the dir without deleting everything with the same name, regardless of extension.
