### ISSUE TITLE
我希望可以加入一个数据库的写入插件或提供一个使用数据库的版本

### ISSUE THREAD

**Issue by fxzxmicah** [robiso/wondercms#141]
毕竟数据库更加稳定与可控，而单文件容易损坏。一但数据文件损坏就会被清空，比较麻烦。

**Comment by NicolasCARPi** [comment]
WonderCMS是一个无数据库的CMS，我认为拥有一个真正的数据库后端超出了这个项目的范围，因为这个项目的目标是小而快。 如果要使用真实数据库，则应使用其他项目。

**Comment by fxzxmicah** [comment]
我可以理解这样的初衷，直接HTML写入也很好用，但是我无法直接修改数据文件，修改后数据文件由于我不清楚的原因会被清空，这是特性还是bug呢？如果能解决这个问题，没有数据库也可以接受。我不一定可以时时刻刻在线更新数据，所以很困扰。

**Comment by robiso** [comment]
Can you provide an example of what you're trying to achieve with a plugin?

To answer your question shortly, it is possible to write data to the database.js file with a custom plugin.

**Comment by fxzxmicah** [comment]
只是将cms的数据写入数据库，仅此而已。只用js不太稳定，而且可能会修改出错导致js文件被清空，而数据库可以更方便的修改。

**Comment by robiso** [comment]
@fxzxmicah, 正如Nicolas已经提到的，使用关系数据库（例如MySQL）超出了本项目的范围。
如果您需要任何协助向数据库写入内容或认为您发现了错误，请重新打开此问题。
您也欢迎使用WonderCMS来实现任何适合您需求的产品，我相信有人也会对不同的产品感兴趣。

**Comment by NicolasCARPi** [comment]
谷歌翻译是一件了不起的事，不是吗？：p

**Comment by fxzxmicah** [comment]
在中国，对于中文百度翻译更准确些ପ( ˘ᵕ˘ ) ੭ ☆

**Comment by robiso** [comment]
我不知道我们正在使用翻译服务。 我在没有任何帮助的情况下进行翻译。 😂

**Comment by fxzxmicah** [comment]
你现在写的是英文?这么神奇的吗？

**Comment by robiso** [comment]
我只是在开玩笑（暗示我正在打字中文）。
遗憾的是我不会说中文，我确实使用翻译服务。

我很惊讶这些天我们可以说任何语言。:)

**Comment by fxzxmicah** [comment]
虽然不是很流利，但是已经很好了。
