### ISSUE TITLE
502 Bad Gateway, nginx version 1.10.3, php7.2, WonderCMS 2.7.0, Certbot SSL encryption

### ISSUE THREAD

**Issue by EntangledLabs** [robiso/wondercms#142]
I have installed everything as required, my nginx config is the same as that from the WonderCMS github page, and all of my permissions are correct, yet I receive a 502 Bad Gateway error.

**Comment by robiso** [comment]
@EntangledLabs 

Did you change these settings in the nginx.conf from the wiki?
```
       # adapt to your server name
        server_name www.wonder-example.com;
        # adapt the path
        root /var/www/wondercms;
```

If the above doesn't work, here's an old NGINX config without any changes required:
```
location ~ database.js {
	return 403;
}

autoindex off;

location / {
	if (!-e $request_filename) {
		rewrite ^/(.+)$ /index.php?page=$1 last;
	}
}
```

Let me know if any of those two solutions worked.

**Comment by EntangledLabs** [comment]
Hello robiso,

Just to be clear, should I remove the php header?

Thank you for the help!

**Comment by robiso** [comment]
@EntangledLabs, I'm not sure what you mean?

To make this easier, can you paste your current nginx.config? If not, simply try the solution from https://github.com/robiso/wondercms/wiki/NGINX-server-config first, make sure you change both **server_name** and **path**.

If that doesn't work, revert all changes you've made to the nginx.conf (before you installed WonderCMS and edited the config), and simply use:

```
location ~ database.js {
	return 403;
}

autoindex off;

location / {
	if (!-e $request_filename) {
		rewrite ^/(.+)$ /index.php?page=$1 last;
	}
}
```

You can also post some more details on what php header you meant in your previous post.

No problem at all, hope we get this sorted out (although I'm no NGINX expert).

**Comment by EntangledLabs** [comment]
I'm actually an idiot. I've been configuring the file in sites-available, not nginx.conf.
I'll reconfigure and get back to you

**Comment by robiso** [comment]
We're only human, don't stress about it. Let me know how it goes. 👍

**Comment by EntangledLabs** [comment]
Hello robiso,

Turns out, the wiki is wrong: the file to be edited is not /etc/nginx/nginx.conf, it should be /etc/nginx/sites-available/<FILENAME HERE>.

I think I'll just reinstall with apache2, but thank you for the help!

**Comment by robiso** [comment]
@EntangledLabs, just to make sure (and since I'm not running NGINX), you got WonderCMS working on your server by editing the sites-available file?

Did you use the config from the wiki or the mini one pasted above?
If there's anything else you needed to do, please let me know and you'll be added to our official "special contributors" page on wondercms.com

**Comment by NicolasCARPi** [comment]
> Turns out, the wiki is wrong: the file to be edited is not /etc/nginx/nginx.conf, it should be /etc/nginx/sites-available/.

Wrong is a point of view. It is entirely valid to add configuration to `nginx.conf` file. Some distributions will have nginx with the site-available/site-enabled folders, others will not.

I have edited the wiki to reflect this.

**Comment by robiso** [comment]
@NicolasCARPi, cheers for clarifying and thanks for the wiki edit. :tada:
