### ISSUE TITLE
array_column() expects parameter 1 to be array

### ISSUE THREAD

**Issue by jult** [robiso/wondercms#143]
I get a redirect loop when trying to install, the log gives this php warning (with php-fpm and NGINX):

PHP message: PHP Notice:  Trying to get property 'pages' of non-object in /x/index.php on line 370
array_column() expects parameter 1 to be array, null given in /x/index.php on line 327

**Comment by robiso** [comment]
@jult, seems like there might be another issue. Can you answer a couple of questions so we can get a better understanding of what could be the issue:

1. Does your server meet the requirements for running WonderCMS? It currently seems the database.js wasn't created and thus other things are failing.
2. Can you check if there's a database.js file created? If there isn't any, than this might be the issue.
3. Are you using a local server? This might be a permissions issue.
4. If there is a database.js created, please paste the contents of it.

WonderCMS requirements:
1. PHP version 7.1 or greater
  -  mbstring extension
  - Zip extension
- mod_rewrite module enabled

**Comment by robiso** [comment]
@jult, please let us know if you require any support by answering the questions above.
Closing issue, please re-open if it's still relevant to you.
