### ISSUE TITLE
[Fix] Catch SSL certificate validation issues with curl under IIS

### ISSUE THREAD

**Issue by romannl** [robiso/wondercms#154]
I had trouble downloading plugins with PHP 7.3 as FastCGI under IIS. The script was executing:
wCMS::alert('success', 'Installed successfully.');
But nothing was installed. When I was debugging, I noticed the cause was curl with error: "SSL certificate problem: unable to get local issuer certificate".
I paste here the code I used to:
1. "fix" the issue (real fix for Windows is to use winssl instead of openssl for compilation of curl)
2. Show more meaningful alerts. I think it would be useful to include this in your code.
I dont know how to create pull requests with diff, so here I paste the code, in case it is useful:

```
				$zipFile = __DIR__ . '/files/ZIPFromURL.zip';
				$zipResource = fopen($zipFile, "w");
				$ch = curl_init();
				curl_setopt($ch, CURLOPT_URL, $addonURL);
				curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
				curl_setopt($ch, CURLOPT_FILE, $zipResource);
+++				curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // potentially dangerous
+++				curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2); // somehow mitigate the danger
+++				curl_setopt($ch, CURLOPT_FAILONERROR, true);
				curl_exec($ch);
+++				$curlError = curl_error($ch);
				curl_close($ch);
+++				if ($curlError) {
+++					wCMS::recursiveDelete(__DIR__ . '/files/ZIPFromURL.zip');
+++					wCMS::alert('danger', 'Error downloading ZIP file. ' . $curlError);
+++					wCMS::redirect();
+++				}
+++				if (filesize($zipFile)<=22) { // minimum zip size
+++					wCMS::recursiveDelete(__DIR__ . '/files/ZIPFromURL.zip');
+++					wCMS::alert('danger', 'Empty ZIP file.');
+++					wCMS::redirect();
+++				}
				$zip = new ZipArchive;
				$extractPath = __DIR__ . '/' . $installLocation . '/';
				if ($zip->open($zipFile) != 'true' || (stripos($addonURL, '.zip') != true)) {

```

Regards

**Comment by robiso** [comment]
Will include a more descriptive error description in experimental 3.0.0. Pull request incoming.

If you want, you can check the wiki for the IIS WonderCMS server config:
https://github.com/robiso/wondercms/wiki/IIS-server-config

**Comment by robiso** [comment]
Pull request merged, we've included the more descriptive errors in the latest experimental 3.0.0 version.
