### ISSUE TITLE
DATA LOSS  "menuItems": null in database.js

### ISSUE THREAD

**Issue by RarogCmex** [robiso/wondercms#161]
It's my first project with wondercms. I create an image (and resize it) in Summernote editor in About your website part and suddendly get full database loss:
`~ # cat /opt/srv/wondercms/database.js
{
    "config": {
        "dbVersion": "2.7.0",
        "menuItems": null
    }
}~ # 
`
I don't know what happened. I used following filenames:
`~ # ls /opt/srv/wondercms/files
'империум человека стилизация под герб РФ.jpg'            'Проект империум человека широкое лого среднее качество.jpg'
'Проект империум человека Классическое красное лого.jpg'
~ # 
`
I will submit full dump of site when I could download archive from my server.

**Comment by RarogCmex** [comment]
[wondercms-error.tar.gz](https://github.com/robiso/wondercms/files/3827488/wondercms-error.tar.gz)

**Comment by RarogCmex** [comment]
Nginx shows: 
Warning: array_column() expects parameter 1 to be array, null given in /opt/srv/wondercms/index.php on line 327
Warning: array_search() expects parameter 2 to be array, null given in /opt/srv/wondercms/index.php on line 327
Warning: array_values() expects parameter 1 to be array, null given in /opt/srv/wondercms/index.php on line 331
Warning: Cannot modify header information - headers already sent by (output started at /opt/srv/wondercms/index.php:327) in /opt/srv/wondercms/index.php on line 653

**Comment by RarogCmex** [comment]
`rarogcmex@RarogCmexEngine ~ $ curl http://skarchive.org.ru:88/
<br />
<b>Warning</b>:  array_column() expects parameter 1 to be array, null given in <b>/opt/srv/wondercms/index.php</b> on line <b>327</b><br />
<br />
<b>Warning</b>:  array_search() expects parameter 2 to be array, null given in <b>/opt/srv/wondercms/index.php</b> on line <b>327</b><br />
<br />
<b>Warning</b>:  array_values() expects parameter 1 to be array, null given in <b>/opt/srv/wondercms/index.php</b> on line <b>331</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /opt/srv/wondercms/index.php:327) in <b>/opt/srv/wondercms/index.php</b> on line <b>653</b><br />
`

**Comment by robiso** [comment]
Hi @RarogCmex, thanks for the report.

Is there any way you can reproduce this?

**Comment by RarogCmex** [comment]
1. I don't know, but I'll try this. I'll have to reinstall ones.
2. PHP 7.2.22 (fpm-fcgi)
3. nginx version: nginx/1.16.1
nginx/php-fpm.

**Comment by RarogCmex** [comment]
Ok, I couldn't reproduce it. 
I also delete .htaccess file. May it cause error?

**Comment by robiso** [comment]
@RarogCmex .htaccess should not make any difference, as you are on an NGINX server. The htaccess file is required only for Apache servers.

Did you go through editing the NGINX server config? https://github.com/robiso/wondercms/wiki/NGINX-server-config

I'm not sure what could of went wrong and this is the first case that's ever been reported that corrupted a database.

**Comment by RarogCmex** [comment]
@robiso At this moment I 'm healing anxiety depressive syndrome so I almost sure that I so unlucky person. But I found another bug that seems like feathure: [port forwarding issues](https://github.com/robiso/wondercms/issues/164)

**Comment by robiso** [comment]
@RarogCmex no a problem at all and no worries. :)

If you somehow manage to reproduce the bug, please reopen this issue.
You should check that thread and possibly provide them with your server config (and removing all the necessary personalized information).
