### ISSUE TITLE
[2.7.0, 3.0.0?] Web port related issues and port forwarding

### ISSUE THREAD

**Issue by RarogCmex** [robiso/wondercms#164]
I use a server that internally occupy 80 web port (http/80) so I changed nginx listen directive to listen 88 port. And external http/80 connections are forwarded to 88 port. Just the same web site:
http://skarchive.org.ru/
If we click example page then we been forwarded http://skarchive.org.ru:88/example... And that functions for all links. For example main page «Главная страница» redirects to http://skarchive.org.ru:**88**/главная-страница
I don't sure that a proper behaviour.

**Comment by notcarbide** [comment]
Seems like an issue with your configuration for port forwarding.

Would you be willing to share what your .conf files look like?

**Comment by StephanStanisic** [comment]
Hi @RarogCmex,

This is actually expected behavior, this is in place in order to make WonderCMS work on non-port 80/443 installations. (Like when hosting locally at `http://localhost:5000`)

I've can remember a forum post where the solution was to just remove the port detection system out of `index.php`. 

@robiso is there a option to default to no extra port in the `$Wcms->url()` function? (for when behind a reverse proxy like now)

Also, a nicer solution is to actually use port 80. What is stopping you from using port 80?

**Comment by robiso** [comment]
@RarogCmex, we've had a similar thread in the past which might be helpfup.

Comment from that thread
> You can set it's value using [fastcgi_param](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/) in nginx config. You can aslo modify it in PHP script as regular variable, so there is no need to introduce additional variables and change body of url() . In your specific case, you might want to [hardcode SERVER_PORT value as 80](https://serverfault.com/questions/256191/getting-correct-server-port-to-php-fpm-through-nginx-and-varnish). If for some reason that wouldn't work, there are other ways like using [sub_filter module](http://nginx.org/en/docs/http/ngx_http_sub_module.html) to rewrite URLs in HTML content.

Link to issue/discussion: https://github.com/robiso/wondercms/issues/47

**Comment by robiso** [comment]
@StephanStanisic, I don't believe so. We'll have to glance over this 👍

**Comment by RarogCmex** [comment]
@StephanStanisic That's because 80 ports in my keenetik router (server) has already used in my local network so I had to use 88 port internally. 
Yes, I may just open 88 port additionally so all my links are become working... but I want to ask you,  should configs to set default port parameters be provided?

**Comment by RarogCmex** [comment]
Yes, @robiso that is my case. But I'll think however should I just forward 88 port...

**Comment by robiso** [comment]
@RarogCmex, glad the above solution/post managed to solve it for you!
🚀
