### ISSUE TITLE
[WonderCMS 3.0.0 beta] Notice in plugin/theme install/update script makes redirection fail

### ISSUE THREAD

**Issue by StephanStanisic** [robiso/wondercms#165]
When php notices are enabled, after installing a plugin/theme the redirection fails if gzip is disabled:

**Notice**: Only variables should be passed by reference in /var/www/html/index.php on line 947

**Warning**: Cannot modify header information - headers already sent by (output started at /var/www/html/index.php:947) in /var/www/html/index.php on line 1322

**Comment by StephanStanisic** [comment]
Possible solution:
```
947c1,2
< $folderName = array_pop(explode('/', str_replace('/archive/master.zip', '', $url)));
---
> $folders = explode('/', str_replace('/archive/master.zip', '', $url));
> $folderName = array_pop($folders);
```

**Comment by robiso** [comment]
Nice catch @StephanStanisic 👏 
I'll include this fix and run it for a test

**Comment by robiso** [comment]
Fix merged with latest update.
Thanks for another awesome fix @StephanStanisic!

Closing issue.
