### ISSUE TITLE
session_regenerate_id();

### ISSUE THREAD

**Issue by 2nlin3** [robiso/wondercms#167]
Установлена последняя версия PHP 7.3.7. При авторизации происходит перенаправление на главную страницу, сессия не сохраняется, ошибки авторизации не видно, пользователь не проходит авторизацию.

Удалил строку с кодом session_regenerate_id(); и авторизация работает.

**Comment by robiso** [comment]
Translation:

> The latest version of PHP 7.3.7 is installed. When authorization is redirected to the main page, the session is not saved, authorization errors are not visible, the user does not pass authorization.
> 
> Deleted the line with the code session_regenerate_id (); and authorization works.

This seems to be an issue introduced in 7.3+. 
**I strongly suggest we do not remove this, as it's in place to prevent session hijacking/fixation.**
We've gotta find a workaround for this.

**Comment by robiso** [comment]
@2nlin3, are you using WonderCMS 2.7.0 or 3.0.1 beta?
@2nlin3, вы используете бета-версию WonderCMS 2.7.0 или 3.0.1?

**Comment by 2nlin3** [comment]
Использую версию WonderCMS 2.7.0. Если заменяю строку session_regenerate_id(); на строку session_destroy(); то авторизация не проходит и нет ошибок в логах PHP. Если заменяю строку session_regenerate_id(); на строку session_unset(); то авторизация работает. Моя проблема решена. Благодарю за ваши ответы!

Мне нравится WonderCMS! Это отличная идея движка для сайта!

**Comment by robiso** [comment]
@2nlin3 

Я не думаю, что замена session_regenerate_id является решением.
Мое предложение состояло в том, чтобы добавить session_destory () или unset (), или оба, ДО сессии_regenerate.

Можете ли вы дать еще одну попытку?

Кроме того, спасибо за комплименты, рад, что вы наслаждаетесь WonderCMS!


I don't think replacing session_regenerate_id is the solution.
My suggestion was to add session_destory() or unset() or both BEFORE the session_regenerate.

Can you please give this another try?

Also, thanks for the compliments, glad you're enjoying WonderCMS!

**Comment by 2nlin3** [comment]
Добавил строку session_unset(); перед строкой session_regenerate_id(); и функция авторизации не работает.

Добавил строку session_destroy(); перед строкой session_regenerate_id(); и функция авторизации не работает.

Работает авторизация только после замены строки session_regenerate_id(); на строку session_unset();

**Comment by robiso** [comment]
Большое спасибо за то, что попробовали это.
Я думаю, что у меня есть окончательное решение.

Если вы можете подтвердить, что это работает, я отправлю исправление с новой бета-версией 3.0.2 в следующие дни.

Перед session_regenerate_id (), пожалуйста, попробуйте поставить:
session_start ();

Итак, конечный результат должен выглядеть так:
```
session_start();
session_regenerate_id();
```

**Comment by robiso** [comment]
@2nlin3 please check the comment above.
@2nlin3 пожалуйста, проверьте комментарий выше

**Comment by 2nlin3** [comment]
Этот код не работает:
```
session_start();
session_regenerate_id();
```

Этот код вызывает ошибку 502:
```
$sid = session_create_id();
session_write_close();
session_id($sid);
session_start();
```
Ошибка: recv() failed (104: Connection reset by peer) while reading response header from upstream

**Comment by 2nlin3** [comment]
Устновил PHP Version 7.4.0RC6. В лог файле нашёл ошибки:
```
Error: Call to undefined function mb_internal_encoding()
Uncaught Error: Call to undefined function mb_strtolower()
```

Я нашёл в чём проблема. У меня есть домен и я установил CMS в субдомен. На основном домене автоматически создаётся PHPSESSID и CMS тоже создаёт PHPSESSID. После авторизации использовался PHPSESSID из основного домена. Если удалить все файлы COOKIES функция session_regenerate_id(); работает и я могу авторизоваться.
