### ISSUE TITLE
unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by camillo777** [robiso/wondercms#175]
Hello after unzipping the CMS I have got an error.
Complete error is:

PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/wondercms/index.php on line 14

Software versions:

Server version: Apache/2.4.25 (Debian)
Server built:   2019-10-13T15:43:54

PHP 7.0.33-0+deb9u6 (cli) (built: Oct 24 2019 18:50:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u6, Copyright (c) 1999-2017, by Zend Technologies

**Comment by robiso** [comment]
Hello @camillo777.

To debug this easier, please answer the following:

1. Which WodnerCMS version are you trying to run?
2. WonderCMS version 3.0.0+ requires PHP 7.2 or higher.
3. Do you have the following modules enabled?
    - mbstring extension
    - Zip extension
    - mod_rewrite module enabled

**Comment by camillo777** [comment]
Hello @robiso here the info (all 3 yes):

**Version:**
WonderCMS-2.7.0.zip

**php -m**
```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
**mbstring**
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
**zip**
zlib

[Zend Modules]
Zend OPcache
```

**apache2ctl -M**
```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 reqtimeout_module (shared)
 **rewrite_module** (shared)
 setenvif_module (shared)
 status_module (shared)

```

**Comment by robiso** [comment]
@camillo777, can you try bumping your PHP version to at least 7.1 and see if it solves the issue?

https://stackoverflow.com/a/51568547

**Comment by camillo777** [comment]
Hello @robiso 
I know this could maybe solve the issue, but I cannot upgrade due to another app on the same server which requires 7.0 by now.
Somewhere in the docs I read that wondercms 2 could be compatible with php 5.5 and up.

**Comment by StephanStanisic** [comment]
I think if you would just find-replace "const" to "" in index.php you'd solve this problem. I'm not sure what kind of 7.1+ features WonderCMS uses but if it's just the constants, you can just remove the `const`.

**Comment by robiso** [comment]
Closing this issue.

@camillo777 feel free to comment or reopen if necessary.

**Comment by camillo777** [comment]
Hello @robiso @StephanStanisic 
it seems I was able to solve it; removed visibility modifiers (public) from this constant line: 

`const MIN_PASSWORD_LENGTH = 8;`

See this answer for reference:
https://stackoverflow.com/questions/51567998/parse-error-syntax-error-unexpected-const-t-const-expecting-variable-t-v

The ability to specify the visibility of class constants was only added in PHP 7.1

**Comment by robiso** [comment]
@camillo777 thank you for getting back with more information.

Keep in mind if you make any changes to your index.php and if you update WonderCMS via the 1-click updater, all the changes you've made to index.php will be overwritten.

**Comment by StephanStanisic** [comment]
I'd like to mention that with Nginx it's actually pretty easy to use 2 php versions, since multiple php versions can be installed next to each other.
When installing php, for example `7.0` and `7.2` they have their own folder with their own php.ini etc. With Nginx you can set the php version on a site basis, just by changing the virualhost config. For example: (inside the `server` block)
```
location ~ \.php$ {
       include snippets/fastcgi-php.conf;

       # With php-fpm (or other unix sockets):
       fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
}
```
You can change `7.0` here for any other php version installed (they are listed in `/etc/php`)

**Comment by camillo777** [comment]
@robiso @StephanStanisic 
Hello again, just I am wonder-ing if version of php >7 is really required for wonder CMS.
Because the CMS is so lightweight and minimal that it's adoption could be improved maybe by more pho version compatibility. Even version 3 could benefit from this if no php feature is really required. Just my idea.

**Comment by robiso** [comment]
@camillo777, a version greater than PHP 7.2 is actually required due to the new functionality that was built for WonderCMS (3.0.0+)

Additionally, using any version lower is considered a risk, since older PHP versions don't receive security patches anymore.

However, older versions of WonderCMS (2.7.0 and lower) should work fine with older PHP versions.
