### ISSUE TITLE
[Feature request] Adding blocks to `pageListener`

### ISSUE THREAD

**Issue by StephanStanisic** [robiso/wondercms#176]
Currently the WonderCMS `pageListener` hook returns the following paths: `title`, `keywords`, `description` and `content`. 

I would think that blocks, like the `<?= $Wcms->block('subside') ?>` should be added into the `pageListener` hook.

This would also add a solution to #160 into the WonderCMS core, without editing a lot of server config.

**Comment by robiso** [comment]
@StephanStanisic, thanks for the suggestion, this has been added in today's changes.
The latest version (stable) will be released tomorrow (Jan 1st 2020).

🚀
