### ISSUE TITLE
login URL doesn't work on local setup

### ISSUE THREAD

**Issue by vemman** [robiso/wondercms#18]
@robiso 
I liked the demo very much, so installed on local machine to play around.

On windows machines admin url is malformed
Instead of _http://localhost/works/wondercms/loginURL_ I get _http://localhostd/Works/wondercms/loginURL_

I believe even if my work was inside apache's htdocs, I will still see the drive letter

**Windows Setup**
Apache 2.4, PHP7 > in **C** drive
My works are under **D:\works\work_sub_folder**

**My Solution**

I replaced INC_ROOT in `function url` with this `dirname($_SERVER['SCRIPT_NAME'])`

`public static function url($location = null) {
    return (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 'https://' : 'http://').$_SERVER['HTTP_HOST'].str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace('\\', '/', INC_ROOT))."/{$location}";
}`

**Comment by robiso** [comment]
@vemman thank you for reporting this, we'll check it out and reply back shortly.
I also changed this issue title from "admin URL not proper" to "login URL doesn't work on local setup" for clarity.

**Comment by robiso** [comment]
@vemman, to ensure we don't break functionality - as this solution hasn't been tested widely, we'll add a documentation link for cases like this.

Thanks for reporting and finding a solution.

**Comment by robiso** [comment]
Added this solution to our new wiki. https://github.com/robiso/wondercms/wiki/Login-URL-doesn't-work-on-local-setup

Closing as we have a solution posted at the above link. Thanks @vemman!
