### ISSUE TITLE
Renaming page without changing title changes slug

### ISSUE THREAD

**Issue by StephanStanisic** [robiso/wondercms#185]
There seems to be a bug which renames existing pages to pages with prefixes.

Example/steps to reproduce
-    Install a clean version of WCMS.
-    Open Settings -> General.
-    Click on "Home".
-    Click outside the input without changing the title (note that the previous slug was "home").
-    After page is refreshed, new slug is "home-2" and "home" doesn't exist any more.

This was thought to be a problem of [StephanStanisic/plugin-plainadmin](https://github.com/StephanStanisic/plugin-plainadmin), but also occurs without it being installed. Related issue: https://github.com/StephanStanisic/plugin-plainadmin/issues/1

**Comment by robiso** [comment]
@StephanStanisic, thanks for reporting, will look into it and provide a 3.0.5 update/patch.

**Comment by robiso** [comment]
This has been fixed with the latest 3.0.5 update (along with some other minor improvements).
Happily closing issue! :)

Thanks @StephanStanisic!
