### ISSUE TITLE
Question: Second Admin / Publisher Account possible?

### ISSUE THREAD

**Issue by alorson** [robiso/wondercms#191]
Hi, is it possible to setup a Second Account, for example to managed the Content of the CMS? 
So i have an Superadmin, and a Admin (+/- Some rights to Change something). 
Did found a way to insert a second user.

**Comment by StephanStanisic** [comment]
Hi Alorson,

In the current state of WonderCMS it is not possible to create a second admin user, as only one (hashed) password is stored in the database.
