### ISSUE TITLE
[PLEASE VOTE] Live communication channel/tool (Discord, Slack, alternatives)?

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#193]
This discussion came about on the official WonderCMS Twitter: https://twitter.com/simonwestghost/status/1238900148497002496 by @simonwestghost respectively.

# What tool would you prefer to communicate live?

1. Discord.
2. Slack.
3. Teams
4. Alternatives -> please specify.

## Please vote by replying with a number.

**Comment by StephanStanisic** [comment]
I think that slack would be a great (professional) option.

The thing with all these options is that they are centralized, and I personally don't favour centralized systems. I would suggest matrix (matrix.org, riot.im) as a decentralized and secure alternative to slack/ discord. With riot as your interface it looks almost 1:1 to slack/discord.

Slack/discord is used more in the industry, so more dev's will already have slack/discord accounts.

Anything goes as long as it's not Microsoft(tm) Teams(r)(c)(rm).

**Comment by robiso** [comment]
I've got another vote from @slavenstancic - voted for Slack.
I'm on the same boat myself, so unless everyone else decided to go against it, the choice is becoming pretty clear.

**Comment by StephanStanisic** [comment]
Slack it is then

**Comment by RarogCmex** [comment]
1. Discord
4. Telegram

**Comment by MasterIO02** [comment]
1. Discord: essentially because that's what I'm using everyday, and that would be more practical to use for me.

**Comment by cngohar** [comment]
4- facebook group?
4- html5chat?

**Comment by foxeo** [comment]
4 hi.tv    On Wednesday, April 8, 2020, 07:13:16 AM EDT, cngohar <notifications@github.com> wrote:  
 
 


4- facebook group?
4- html5chat?

**Comment by robiso** [comment]
Closing issue since Slack was already created.
Thanks to everyone for your valuable input.

Join us for a chat:
https://wondercms.slack.com
