### ISSUE TITLE
WonderCMS 3.0.7 syntax error 

### ISSUE THREAD

**Issue by kkarthik23** [robiso/wondercms#196]
**Wonder CMS version 3.0.7**

Using `php version 7.0.33-0` i get the below error
"PHP message: PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/wondercms/index.php on line 21"

using php fpm and nginx

Could someone please assist?

**Comment by kkarthik23** [comment]
> **Wonder CMS version 3.0.7**
> 
> Using `php version 7.0.33-0` i get the below error
> "PHP message: PHP Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/wondercms/index.php on line 21"
> 
> using php fpm and nginx
> 
> Could someone please assist?

Sorrry I just noticed i need php 7.2  for it to work

**Comment by robiso** [comment]
@kkarthik23, cheers for reporting back.
Closing issue, please feel free to continue commenting if you have any questions.
