### ISSUE TITLE
[SOLVED] Nginx & PHP-FPM Issue

### ISSUE THREAD

**Issue by greendruid** [robiso/wondercms#20]
Hello!

Thank you for WonderCMS! It's very easy and very powerfull engine. Looks like a magic :)
I have an issue about WonderCMS at the Nginx environment. I can't to get access to loginURL or example page. 
I try to use the recomendation from this page: https://github.com/robiso/wondercms/wiki/NGINX-server-config  . But in PHP-FPM 
Message in the Nginx logfile: 
`
[23-Mar-2017 14:12:48 Asia/Singapore] PHP Notice:  Undefined index: page in /var/vhosts/stty/www/index.php on line 91
`
Thank you!

**Comment by greendruid** [comment]
OK. How I can disable rewrite?

**Comment by robiso** [comment]
Helllo greendruid!

Thank you for reporting the issue and posting a solution before we even got to help you.
We've replaced `rewrite ^(.+)$ /index.php?page= break;` with  `rewrite ^/(.+)$ /index.php?page=$1 last;`.

Can you please confirm this is correct the fix and we'll mark this issue solved.
Thank you very much.

**Comment by sttyru** [comment]
Hello!

**Thank you for your quick reply!**
Positive. I can to confirm that this issue solved. :smile_cat: 

_--- OFFTOP ---

I have a one little question about feature request. Can I add topic with this to Issues?_

**Comment by robiso** [comment]
Fix updated to wiki and readme, marking this solved.
Thank you very much! :+1:

**Comment by robiso** [comment]
Just to add a reply to your previous edit, yes you can simply write the feature request either on the forum or under the GitHub "Issues" tab about future improvements.
