### ISSUE TITLE
There is a problem with the summernote editor

### ISSUE THREAD

**Issue by fxzxmic** [robiso/wondercms#203]
![image](https://user-images.githubusercontent.com/54622331/82446375-20608a80-9ad9-11ea-9af7-96b3087c780b.png)
The edit bar of the summernote editor does not display icons, and the F12 console does not report any error.
I use **lightblue** theme.

**Comment by robiso** [comment]
What version of WonderCMS are you using?
Additionally, what version of Summernote is installed?

**Comment by fxzxmic** [comment]
They're all the latest versions.

**Comment by robiso** [comment]
@fxzxmic this seems a bit unusual, as all latest versions are installed on the demo (https://www.wondercms.com/demo/) and they work as expected?

1. What browser/OS are you using?
2. Can you try clearing your browser cache or try out the editor in a private browsing mode to rule out a caching issue?

**Comment by fxzxmic** [comment]
Maybe it's my problem. It didn't happen after I changed the theme.

**Comment by robiso** [comment]
If I understand correctly, it started working?
Closing issue, please re-open it if I misunderstood
