### ISSUE TITLE
[Recomendation] include instructions for Apache2 configuration to support WonderCMS

### ISSUE THREAD

**Issue by TheMagicNacho** [robiso/wondercms#204]
**Issue:**  Ubuntu based LAMP servers create a 404 error upon initial instalation.
**Discussion:**  The Apache Log will cite issues with the re-write engine. This issue is seperate from .htaccess and extends byond already posted instalation instructions.
STEPS TO RECREATE: Install LAMP on a new instance. Install WonderCMS. Direct browser to localhost/wondercms
Browser will show 404 error dispite .htaccess confingured correctly.

The issue is with the Apache2 config file located in /etc/apache2/apache2.conf 
The system administrator needs to locate their localhost directory within the config file and change
`AllowOverride None` to `AllowOverride All`

This is what an example configured directory would look like:
```
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

**Recomendation:** Include steps to overcome issue within the troubleshooting steps in the wiki or include the configuration change in the default instalation instructions.

**Comment by robiso** [comment]
Hi @TheMagicNacho.

Thanks for providing valuable info and making it easier for everyone else that runs into the same issue.

This has now been added to the troubleshooting section of the wiki:
- https://github.com/robiso/wondercms/wiki/List-of-common-errors
- https://github.com/robiso/wondercms/wiki/Apache2-configuration---404-page-errors-on-Ubuntu-LAMP

Closing issue, feel free to comment or to continue the discussion.

**Comment by TheMagicNacho** [comment]
> Hi @TheMagicNacho.
> 
> 
> 
> Thanks for providing valuable info and making it easier for everyone else that runs into the same issue.
> 
> 
> 
> This has now been added to the troubleshooting section of the wiki:
> 
> - https://github.com/robiso/wondercms/wiki/List-of-common-errors
> 
> - https://github.com/robiso/wondercms/wiki/Apache2-configuration---404-page-errors-on-Ubuntu-LAMP
> 
> 
> 
> Closing issue, feel free to comment or to continue the discussion.

@robiso no more issues here. I’m glad to help.
