### ISSUE TITLE
Use local static resources

### ISSUE THREAD

**Issue by fxzxmic** [robiso/wondercms#205]
My website network speed is generally faster than the remote server loading static resources, so static resources become the reason why my website speed is slowed down. Therefore, we hope to set a switch to let us choose to use remote or local static resources.

**Comment by fxzxmic** [comment]
In addition, it can also alleviate the possible remote server network failure.

**Comment by StephanStanisic** [comment]
I have tried to make a plugin to do this, only it partially works. 

This plugin forks onto the css and js events and downloads the known remote files + replaces them with local urls. 
This doesn't work for urls added in the theme.php, and any urls added by plugins after this plugin has run (maybe add a 'z' to the name to make it run last.)

Anyway here's the plugin's code, again, partially working.

```php
global $Wcms;
function replace_assets($args) {
	global $Wcms;
	$assets = [
		"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css",
		"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js",
		"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js",
		"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js",
		"https://cdn.jsdelivr.net/gh/robiso/wondercms-cdn-files@3.1.8/wcms-admin.min.css",
		"https://cdn.jsdelivr.net/gh/robiso/wondercms-cdn-files@3.1.9/wcms-admin.min.js",
		"https://cdn.jsdelivr.net/npm/taboverride@4.0.3/build/output/taboverride.min.js",
		"https://cdn.jsdelivr.net/npm/autosize@4.0.2/dist/autosize.min.js"
	];
	foreach($assets as $remote) {
		$name = basename($remote);
		$local = $Wcms->url("plugins/zlocal-cdn/assets/$name");
		$args[0] = str_replace($remote, $local, $args[0]);
		// Download files
		if(!file_exists(__DIR__ . "/assets/$name")) {
			file_put_contents(__DIR__ . "/assets/$name", file_get_contents($remote));
		}
	}
	return $args;
}
$Wcms->addListener('js', 'replace_assets');
$Wcms->addListener('css', 'replace_assets');
```
Put this in `plugins/zlocal-cdn/zlocal-cdn.php`, and create the folder `plugins/zlocal-cdn/assets`

**Comment by fxzxmic** [comment]
@StephanStanisic Thank you for your help, but this plugin has only replaced three JS at the back stage, and the JS that affects the speed of frontpage visiting has not been replaced.

**Comment by fxzxmic** [comment]
@robiso Hope you can consider this when developing and communicating with others who are developing themes and plugins. Many of the static resources in code are directly output without processing. I can't think of any good way to modify them while keeping the original code.The serious problem is that `https://code.jquery.com/` is not accessible in my area without proxy and some other static resources load slowly, so a local static resource is very important. Thank you.

**Comment by robiso** [comment]
WonderCMS core doesn't include jQuery or any popular libraries by default anymore It can be bypassed by using above method or simply forking the project and localising the resources.

There might be some point in the future where we can remove the CDN's, but it seems more useful for it to be loaded through CDN's for more people and the users that need to use resources locally, can do it pretty easily.

Closing issue, please feel free to reopen or continue commenting for additional discussions.
