### ISSUE TITLE
[Bug] - Backup fails with 100MB+ backups

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#212]
When the user tries to backup a website larger than a few 10MBs, the link leads to a 404 even though the ZIP backup is successfully created.

**Comment by robiso** [comment]
@slavenstancic, since you tried to fix with the latest release but couldn't reproduce the issue - could you please specify your suspicion as to why this wouldn't be working on some servers? My instance is Apache, for example, could it be related to server types?.

**Comment by slavenstancic** [comment]
@robiso I suspect that the issue is in the server settings or php.ini. I.e.:

- `post_max_size` and `upload_max_filesize` in php.ini.
- Nginx has `client_max_body_size`
- Apache has option in htaccess the `php_value upload_max_filesize` and `php_value post_max_size`

There is also max execution time.

**Comment by robiso** [comment]
@slavenstancic you're completely correct.

In my case, the limit was 128M and these were the settings below (provided with explanations):
 **post_max_size** ->  Sets max size of post data allowed. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize. Generally speaking, memory_limit should be larger than post_max_size.
 **upload_max_filesize** ->  The maximum size of an uploaded file. 

The above two should be matching. 

@slavenstancic thank you, those were the exact two properties to edit.
Closing this, as it's not a WonderCMS issue.
