### ISSUE TITLE
index.php: input for password missing placeholder attribute

### ISSUE THREAD

**Issue by YawningHippo** [robiso/wondercms#214]
In the **index.php** file found in the latest download of Wonder CMS (3.1.1), the `public function loginView(): array` is missing the placeholder attribute for the password field:

`<input type="password" class="form-control" id="password" name="password" placeholder="password" autofocus>`

**Comment by robiso** [comment]
@YawningHippo, this has been deployed with latest 3.1.2 release.
Thanks @YawningHippo!
