### ISSUE TITLE
[Bug] Can't change background image in Parallax theme 

### ISSUE THREAD

**Issue by Imerion** [robiso/wondercms#215]
I tried using the Parallax theme for a page. It works fine and looks good, apart from one small problem. On the Current Page settings, none of the drop-downs seem to save their selection. I have tried switching background image and parallax type, but none of the changes get saved.

WonderCMS: 3.1.1
Parallax theme: 3.0.3
Browser: Firefox 80

**Comment by Imerion** [comment]
Tried it with a few other browsers too, but doesn't work there either. Does anyone know the database entry for the background, then I could add it manually and try.

**Comment by robiso** [comment]
Hello @Imerion.

Thanks for the bug report.

Seems like the theme might have to be updated by @stephanstanisic
Can you set the background directly in your CSS file? How familiar are you with CSS?

**Comment by Imerion** [comment]
Hi @robiso Thanks for your answer!

I'm quite used to CSS, so I could do that. Problem is that would apply for all pages, but the cool thing with the theme setting is different background pictures can be applied to different pages. I guess the theme is supposed to add a setting in the database file, but I was not able to figure out that one.

**Comment by robiso** [comment]
@Imerion after a quick inspection, it seems that the plugin is using "background" property on the page itself in the database.

What I would suggest (until this is fixed by @stephanstanisic, since we aren't using fieldSave anymore and this is the console log error when trying to save the background.

1. Create a backup of your website.
2. On the page you want to change the header image in database.js, add a "background" property in the array and enter the URL.
3. Save the database.
4. I believe this should work, but not completely sure since Stephan is the theme author.

**Comment by Imerion** [comment]
@robiso Thanks for your help! I tried adding this property line:

"background": "http://www.path/to/my/image.jpg",

But got a blank background. Should the line read different perhaps?

**Comment by robiso** [comment]
@Imerion I used an old WonderCMS version to figure this out and the solution is to enter the image name, without the path:
```
        "home": {
            "title": "Home",
            "keywords": "Keywords, are, good, for, search, engines",
            "description": "A short description is also good.",
            "content": "<h1>Website alive!<\/h1>\n\n<h4><a href=\"http:\/\/wondercms.com\/devPrepare\/307\/wondercms\/loginURL\">Click to login.<\/a> Your password is: <b>AWZMRNSL<\/b><\/a><\/h4>",
            "background": "hero.png"
        },
```
Considering this issue fixed, however, @stephanstanisic will have to look into applying this fix to the theme itself.

**Comment by Imerion** [comment]
@robiso Thanks, that worked! Placing the image in the "data" folder and adding the above line displayed the image at the expected place.

**Comment by robiso** [comment]
@Imerion glad this helped and thanks for confirming!

I'll leave this thread open until the theme is fixed.

**Comment by robiso** [comment]
This seems to be fixed in the latest versions of WonderCMS and Parallax :) Thank you @Imerion

**Comment by Imerion** [comment]
Excellent, thanks!

**Comment by robiso** [comment]
@Imerion thank you very much!

Glad to see users supporting WonderCMS, it used to be silent around here.
Enjoy the new update - I've pushed an additional update to the Parallax theme, let us know if you have any issues.
