### ISSUE TITLE
[SOLVED - update deployed] Depreciated notice

### ISSUE THREAD

**Issue by emdashbuck** [robiso/wondercms#22]
Hi there, I'm a brand new user of your CMS. Just downloaded and set up a playground.

I got this error:

`Deprecated: Non-static method wCMS::_updateOtherFiles() should not be called statically` on line 37.

Changing line 13 to read: 

`public static function _updateOtherFiles() {` 

This appears to have fixed the problem without breaking anything else.

**Comment by robiso** [comment]
Hello embdashbuck, welcome and thanks for reporting this. Push is fixed to all WonderCMS users, log out and log back in to see the notification for the update.

Cheers!
