### ISSUE TITLE
Accent Page Error

### ISSUE THREAD

**Issue by emersiljr** [robiso/wondercms#223]
I'm trying to create a page that has an "Serviços" accent and is giving an error:
![image](https://user-images.githubusercontent.com/11966757/97234911-8a840680-17c0-11eb-9642-1dcb60f402fc.png)

I use the last version: 3.1.3
Server Windows IIS

**Comment by robiso** [comment]
It seems this might be a Windows IIS issue as works normally on Apache/NGINX type servers.
I'll get back to you after doing some re-search in the following days. The web config might need some modifications.

Thanks for the report @emersiljr.

**Comment by robiso** [comment]
@emersiljr I've tried investigated the above and came to the following:
- it seems you might now have the correct encoding? At this seems to be able to work as the default: 
- https://forums.iis.net/t/1238022.aspx?Problem+characters+with+accents+in+URL

Do you configure your own server or do you have a web host which manages it for you?

**Comment by emersiljr** [comment]
This resolved, in file web.config:
<globalization fileEncoding="utf-8" requestEncoding="utf-8" responseEncoding="utf-8" culture="pt-br"/>

It's working, but my links are showing 2 backslashes "//" instead of one
![wonder-cms-2barras](https://user-images.githubusercontent.com/11966757/100627040-462adf80-3305-11eb-8668-41df0fe2f2b4.png)

**Comment by robiso** [comment]
Is this server running in production?

I found a report which states, that once it was deployed to production, the issue was fixed on it's own:
- https://stackoverflow.com/questions/55101132/iis-redirect-inserting-double-forward-slash

If not, here's another possible solution:
https://forums.iis.net/t/1174772.aspx
which posted the following solution:
```
<rewrite>
  <rules>
    <rule name="RemoveDoubleSlash" patternSyntax="Wildcard" stopProcessing="true">
      <match url="*//*" />
      <action type="Redirect" url="{R:1}/{R:2}" />
    </rule>
  </rules>
</rewrite>
```

Let me know if this worked.

**Comment by robiso** [comment]
@emersiljr, since this topic is over a month old, I will close it.
Please feel free to comment or re-open the issue if necessary.
