### ISSUE TITLE
Page templates

### ISSUE THREAD

**Issue by trajche** [robiso/wondercms#228]
Hi there! I was looking for a really simple CMS for some up-coming sites I am developing and ran into **wondercms**.

I am unable to figure out if it's possible for different pages to have different templates and how that could be done?

Thanks!

**Comment by robiso** [comment]
Hi @trajche.

WonderCMS does not support different templates for different pages by default.
However, it's still possible with a little bit of PHP work.

1. If you create a copy of a theme and customize it, something like this should work for you.
2. In the <head></head> section, you can load additional styles as shown below.
- The below code will load another CSS file if your visitor is on the "home" page.
```
<?php
    if ($Wcms->currentPage = 'home') {
       echo '<link rel="stylesheet" href="linktoYourCSSFile.css">	
    }
?>
```
- Just be mindful of the fact you have to change the _currentPage_ to the actual page you want to load styles on. Same goes with the link to the CSS path.

3. You can then use the same logic for creating the HTML / showing different layouts.
- That way, you can include different CSS files for different pages

Let me know if this helped or if you need any assistance.

**Comment by trajche** [comment]
Thanks @robiso ! I was wondering more about different "themes.php" files for different pages.

For example, I don't know if you use WonderCMS for your own homepage, but how would one go about creating different themes for the pages?

An idea: if you have a page called home and home.php is detected in the main folder, it could use that? I'm thinking about giving it a go and seeing if I can add this functionality.

**Comment by trajche** [comment]
So I modified the source:

```
	/**
	 * Loads theme files and functions.php file (if they exists)
	 * @return void
	 */
	public function loadThemeAndFunctions(): void
	{
		$location = $this->rootDir . '/themes/' . $this->get('config', 'theme');
		if (file_exists($location . '/functions.php')) {
			require_once $location . '/functions.php';
		}

		if( file_exists( $location . '/override/' . $this->slugify($this->currentPage) . '.php' ) ) {

            require_once $location . '/theme/' . $this->slugify($this->currentPage) . '.php';

        } else {

            require_once $location . '/theme.php';

        }


	}
```

This will allow for custom templates inside a **/theme/** folder. For example using the Essence theme if you create a page: **Test** and add a file inside: `/essence/theme/test.php` it will inherit it instead of the default **theme.php**.

Let me know if this is interesting and I should do a PR.

**Comment by slavenstancic** [comment]
@trajche will be added in WCMS 3.2.0, visible change in PR: https://github.com/robiso/wondercms/pull/227. It will work similarly as you described, so each file containing the slug as prefix will be loaded otherwise the default theme.php will be used.
I.e. if you're on home page and you will have home.php in root of active theme, that file will be loaded.

**Comment by robiso** [comment]
Closing issue, as we just pushed out WonderCMS 3.2.0.
