### ISSUE TITLE
Blocks cannot be edited if text start is an HTML tag

### ISSUE THREAD

**Issue by scsmash3r** [robiso/wondercms#23]
By default, you can use HTML tags inside your blocks (like `<b>`, `<table>`, `<div>` and so on), and that goes fine until you are saving your block, and that block is starting from an HTML tag, that is represented as a block (let's say `<div>`).

If so, you can't edit your text anymore and will lose all your content after next saving. Since we are wrapping a text into `<span>` block (and `<span>` is inline element by default), `<div>` or `<p>` element will 'pop-out' of editable `<span>` tag.

**Comment by robiso** [comment]
Can you give a more accurate example, possibly live/web? I don't quite understand when the <div> or <p> pops out, since you're supposed to wrap editable areas in their own <div>'s.

As far as I understand the problem, this doesn't happen with regular content, but only the extra blocks? Or all editable blocks in general?

An example of your code or when this happens will greatly help.

**Comment by scsmash3r** [comment]
To reproduce that kind of problem, the steps are:
1) Install WonderCMS
2) Go to theme.php
3) On line 42 wrap `<?=wCMS::page('content')?>` into `<p><?=wCMS::page('content')?></p>`
4) See the result

In my own theme, I have some misc content (like item prices) wrapped around with a `<p>` tag. And if I will try to store something, that will start as a block element in my content section, this will cause a bug.

**Comment by robiso** [comment]
Thank you very much for the clear explanation.

I've tested out a fixed (unpublished) version pasted below. Can you please do a short test and replace the below index.php with your index.php or just create an extra folder (to avoid you overriding any files) on your server to test this out until we push an official fix.

What I changed in the index.php core file is changed the structure from spans to divs. Please report back as I couldn't break the editor any more in the way you described.

If all tests go ok, we'll push a fix accordingly and credit your bug report and assistance. Please note this index.php below is not for production use and is only for testing purposes.

[index.php.zip](https://github.com/robiso/wondercms/files/916420/index.php.zip)

**Comment by robiso** [comment]
Fix pushed with version 2.0.3. You have been also publicly credited at the following locations:
 - https://www.wondercms.com/whatsnew
 - https://github.com/robiso/wondercms/releases
 - https://github.com/robiso/wondercms
 - https://www.wondercms.com/forum/viewtopic.php?f=8&p=1684
