### ISSUE TITLE
[Feature request] Color-Picker for Essence-Theme

### ISSUE THREAD

**Issue by steinhmor** [robiso/wondercms#230]
I figured out that it is possible to change the colour of the Essence-Theme by editing this ccs-line
`    background-image: linear-gradient(45deg,#29bae4 0%,#ee76ad 100%);`
For me this is an easy thing but I want to offer WonderCMS on my server to people without any CSS-skills. So it would be great to be able to change the two colours in the admin-panel with a simple colour-picker.

**Comment by robiso** [comment]
@steinhmor this has been something @slavenstancic and I discussed last week, not specifically for Essence, but in general.

We'll see what we can do after we release the next version of WonderCMS, which will include subpages and still requires major testing.

Thank you for the suggestion 🍻

**Comment by robiso** [comment]
Closing due to:
- inactivity
- seeing this can be solved within a theme/plugin itself.
