### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by dozych** [robiso/wondercms#231]
php - 7.3

**Comment by dozych** [comment]
uploaded files from site
open website and HTTP ERROR 500

**Comment by dozych** [comment]
after chmod to themes two new problems
```
The following extensions are required: zip Please contact your host or configure your server to enable them.
The following extensions are required: curl. Please contact your host or configure your server to enable them.
```
zip installed, curl installed too
_curl is already the newest version (7.64.0-4+deb10u1)._

**Comment by robiso** [comment]
@dozych 
1. What type server are you running on? (Apache, NGINX, IIS).
2. What version of PHP do you have?
If you can, please also specify which ZIP version you have installed on server.

**Comment by dozych** [comment]
> @dozych
> 
> 1. What type server are you running on? (Apache, NGINX, IIS).
> 2. What version of PHP do you have?
>    If you can, please also specify which ZIP version you have installed on server.

1. 
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29

2. PHP 7.3.26-1+0~20210112.74+debian9~1.gbpd78724 (cli) (built: Jan 12 2021 14:01:18) ( NTS )
- zip is already the newest version (3.0-11+b1).

**Comment by robiso** [comment]
It seems you meet all the minimum requirements for run WonderCMS.
1. To be able to debug this further, could you please provide us with an anonymised php.ini?
2. Have you tried installing any other CMS to see if your server is configured correctly?

**Comment by dozych** [comment]
> It seems you meet all the minimum requirements for run WonderCMS.
> 
> 1. To be able to debug this further, could you please provide us with an anonymised php.ini?
> 2. Have you tried installing any other CMS to see if your server is configured correctly?
oh idk how to make anonymised php.ini
yea, i have installed other cms. like wordpress, datalife engine, octobercms

**Comment by robiso** [comment]
Before you paste your php.ini file, make sure there is no data which you wouldn't want to make public.

It seems these modules either aren't loaded correctly or WonderCMS doesn't have access to them. Have you possibly re-written the permissions to another user on the server, thus making WonderCMS inaccessible to the required packages.

**Comment by dozych** [comment]
> Before you paste your php.ini file, make sure there is no data which you wouldn't want to make public.
> 
> It seems these modules either aren't loaded correctly or WonderCMS doesn't have access to them. Have you possibly re-written the permissions to another user on the server, thus making WonderCMS inaccessible to the required packages.
can i show him in discord?

>

**Comment by dozych** [comment]
now main page working, but after login i got 500 error

**Comment by dozych** [comment]
_PHP version 7.2 or greater_
PHP Version 7.3.26-1+0~20210112.74+debian9~1.gbpd78724
_cURL extension_
cURL | Sterling Hughes
_mbstring extension_
Multibyte Support | enabled
Multibyte string engine | libmbfl
HTTP input encoding translation | disabled
libmbfl version | 1.3.2
oniguruma version | 6.9.4
_Zip extension_
Zip version | 1.15.4
Libzip headers version | 1.5.1
Libzip library version | 1.5.1
_mod_rewrite module enabled_
root@#:~# a2enmod rewrite
Module rewrite already enabled

**Comment by dozych** [comment]
lul, hoster helped me

> The rights to the files and directories were not correct, it was necessary to correct the owner and the group

**Comment by robiso** [comment]
>  **Have you possibly re-written the permissions to another user on the server, thus making WonderCMS inaccessible to the required packages?**

Glad this was the case.
@dozych thanks for getting back and closing this issue.
