### ISSUE TITLE
default menu and modal window

### ISSUE THREAD

**Issue by dozych** [robiso/wondercms#232]
![image](https://user-images.githubusercontent.com/6689424/106000110-82897a80-60bf-11eb-87b3-9540bc9764ad.png)
menu bugged, i dont need that edit icon or wtf is it (i think its in index.php)
modal window (admin panel) dont work
opened empty window and i cant scroll website

**Comment by robiso** [comment]
Closing issue as this is an **theme issue** and **not a WonderCMS core** issue.

Please visit our community for any help for creating your own theme.
A few head ups:
- Your theme seems to be either missing jQuery or Boostrap, which are currently still required for everything to be functional.
- If you want to edit the wcms.admin.css, you will have to fork WonderCMS and modify then include files yourself into your own version of WonderCMS.

If you need help, drop by a message in the community: https://www.wondercms.com/community
- If you do so, you will also have to specify which libraries (CSS or JS) your theme is using. Along with browser and OS problem.

Please note WonderCMS is free and open source and does not have employees.
- People trying to help you are working in their free time, so it might take a longer time for someone to help you out.
