### ISSUE TITLE
error log Parllax theme

### ISSUE THREAD

**Issue by Escuelalibre** [robiso/wondercms#239]
Hi, 

Hope you are doing well. I am a not a experienced user, :) and I have encountered this error log, (you can find below) my host says this is due to a  bug in the WonderCMS code.  Any help will be much appreciated, 

[20-Jul-2021 14:55:53 UTC] PHP Fatal error:  Uncaught TypeError: Return value of SimpleStatistics::getDb() must be an instance of stdClass, null returned in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php:47
Stack trace:
#0 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php(30): SimpleStatistics->getDb()
#1 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/simple-statistics.php(6): SimpleStatistics->init()
#2 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(1167): include('/home/u78780965...')
#3 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(126): Wcms->loadPlugins()
#4 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(15): Wcms->init()
#5 {main}
  thrown in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php on line 47
[20-Jul-2021 14:55:54 UTC] PHP Fatal error:  Uncaught TypeError: Return value of SimpleStatistics::getDb() must be an instance of stdClass, null returned in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php:47
Stack trace:
#0 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php(30): SimpleStatistics->getDb()
#1 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/simple-statistics.php(6): SimpleStatistics->init()
#2 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(1167): include('/home/u78780965...')
#3 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(126): Wcms->loadPlugins()
#4 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(15): Wcms->init()
#5 {main}
  thrown in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php on line 47
[20-Jul-2021 14:55:55 UTC] PHP Fatal error:  Uncaught TypeError: Return value of SimpleStatistics::getDb() must be an instance of stdClass, null returned in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php:47
Stack trace:
#0 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php(30): SimpleStatistics->getDb()
#1 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/simple-statistics.php(6): SimpleStatistics->init()
#2 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(1167): include('/home/u78780965...')
#3 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(126): Wcms->loadPlugins()
#4 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(15): Wcms->init()
#5 {main}
  thrown in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php on line 47
[20-Jul-2021 14:55:55 UTC] PHP Fatal error:  Uncaught TypeError: Return value of SimpleStatistics::getDb() must be an instance of stdClass, null returned in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php:47
Stack trace:
#0 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php(30): SimpleStatistics->getDb()
#1 /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/simple-statistics.php(6): SimpleStatistics->init()
#2 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(1167): include('/home/u78780965...')
#3 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(126): Wcms->loadPlugins()
#4 /home/u787809652/domains/escuelalibredeadultos.com/public_html/index.php(15): Wcms->init()
#5 {main}
  thrown in /home/u787809652/domains/escuelalibredeadultos.com/public_html/plugins/simple-statistics/class.SimpleStatistics.php on line 47

**Comment by robiso** [comment]
Hi @Escuelalibre , it seems the issue is Simple statistics plugin you have installed.

1. Was your website working at any point and it then broke?
2. What version of WonderCMS are you using.
3. What type of server do you have. (Apache, NGINX, IIS)
4. What version of PHP do you have.
5. What version of Summernote do you have?

**Comment by Escuelalibre** [comment]
Hi,

Thank you for your reply,


  1.  Was your website working at any point and it then broke?

Yes, It has been working all time, if the issue comes from Simple statics download, this was downloaded long time before it broke,

  1.  What version of WonderCMS are you using.

/**
 * @package WonderCMS
 * @author Robert Isoski
 * @see https://www.wondercms.com
 * @license MIT
 */

session_start();
define('VERSION', '3.1.4');
mb_internal_encoding('UTF-8');


  1.  What type of server do you have. (Apache, NGINX, IIS)

I am using Hostinger, https://www.hostinger.com/

In 2019 Hostinger converted its Apache HTTP servers to LiteSpeed Web Server (LSWS) to increase the servers' performance. In mid-2020 Hostinger partnered with Google Cloud Platform. In 2021, Hostinger was listed as one of the fastest-growing companies in Europe.

  1.  What version of PHP do you have.

PHP Version 5.6.40

  1.  What version of Summernote do you have?

3.1.1

Hope my answers are good enough,

Best wishes
________________________________
