### ISSUE TITLE
Scrolling strange behavior 

### ISSUE THREAD

**Issue by idnovic** [robiso/wondercms#244]
Hello,

1. normally it is possible to scroll to the top of the page by hitting the top bar of the iPhone/iPad. 

WonderCMS does not support this. 

2. On my Apple Watch I can scroll websites by rotating the wheel on the side. 

WonderCMS does not support this. 

It seems to be a general scrolling issue. 

I am using WonderCMS 3.1.4

**Comment by robiso** [comment]
@idnovic does this also happen with the latest 3.2.0 WonderCMS for you?

**Comment by robiso** [comment]
After some quick research, this seems like it's theme specific:
https://stackoverflow.com/questions/15454998/scrolling-not-working-on-iphone

It should be solved in any theme if `-webkit-overflow-scrolling:touch;` is added. 

Closing issue for now, feel free to reopen it or continue the discussion.

**Comment by idnovic** [comment]
I will try it out tomorrow. Thank you.
