### ISSUE TITLE
Support for build in PHP server

### ISSUE THREAD

**Issue by jellehak** [robiso/wondercms#248]
First of all great CMS. Yet the way to resolve the url path is not very flexible. This also blocks using the build in PHP server to be functional for local testing. ```php -S localhost:1234```

Would be nice to supply the url instead of having the Class to guess it: 

```
$Wcms = new Wcms();
$Wcms->setUrl($_GET['page'] ?? $_SERVER['REQUEST_URI']);
```
or
```
$Wcms = new Wcms(['url'=>$_GET['page'] ?? $_SERVER['REQUEST_URI']]);
```

Or rewrite the parseUrl.
```
public function parseUrl(): string
	{
		$page = $_GET['page'] ?? ltrim($_SERVER['REQUEST_URI'], '/');

		if (!isset($page) || !$page) {
			$defaultPage = $this->get('config', 'defaultPage');
			$this->currentPageTree = explode('/', $defaultPage);
			return $defaultPage;
		}

		$this->currentPageTree = explode('/', rtrim($page, '/'));
		if ($page === $this->get('config', 'login')) {
			return htmlspecialchars($page, ENT_QUOTES);
		}

		$currentPage = end($this->currentPageTree);
		return $this->slugify($currentPage);
	}
```

**Comment by robiso** [comment]
@jellehak thank you for the feedback.

We'll take a look on this and see if we can make any improvements without breaking backwards compatibility.

**Comment by robiso** [comment]
@jellehak we're tried implementing your solution, however the default page didn't work as expected.

An additional example that went wrong with testing was also pages returning a different path with slashes, which kills certain WonderCMS functionality.

We can leave this issue open if any additional improvements would be made (by you or anyone else).

**Comment by robiso** [comment]
@jellehak, this should be fixed with the latest 3.3.3 version of WonderCMS.
Thank you for your suggestions! 🚀 

Closing issue. Please feel free to reopen or continue the dicussion.

**Comment by jellehak** [comment]
Hi @robiso ,

Couldn't really find what has been changed. Luckily I found a different solution by using a router for the build in server.
> This might be useful in the docs or perhaps integrated in repo.

Add the following file `router.php` and run the PHP server with `run with `php -S localhost:4000 router.php`. Or any other port you would use.
```php
<?php
// run with `php -S localhost:4000 router.php`

// Special info request http://localhost:4001/_info
if($_SERVER['REQUEST_URI'] === '/_info') {
    print_r($_SERVER);
    exit();
}

// Delegate to wondercms
if($_SERVER['SCRIPT_NAME'] === '/index.php') {
    $page = ltrim($_SERVER['REQUEST_URI'],"/");
    $_GET['page'] = $page;
}

// let PHP handle it
return false;
```

**Comment by jellehak** [comment]
@robiso sorry I missed it but you already added a previous suggestion (#75) to the wiki. https://github.com/WonderCMS/wondercms/wiki/PHP-built-in-server

**Comment by robiso** [comment]
Hello @jellehak, awesome that you found it. I couldn't respond since I'm still on vacation but happy you found the wiki.
