### ISSUE TITLE
not an issue: some improvement to arabic language and translated the missing ones 

### ISSUE THREAD

**Issue by DaddyMadu** [robiso/wondercms#249]
@robiso hey robiso good day!
i'd like to offer some better translation for arabic language and added the remaining untranslated ones,
have a greate day!
[ar.csv](https://github.com/robiso/wondercms/files/7919606/ar.csv)

**Comment by robiso** [comment]
Hello @DaddyMadu, hope you're doing well.
Thank you for the updates, the plugin has been updated - you're making a better experience for Arabic users which is epic!

Have a nice day as well!
