### ISSUE TITLE
[Possible bug] Wrong file paths in latest WoncerCMS

### ISSUE THREAD

**Issue by Imerion** [robiso/wondercms#252]
I noticed a weird thing when updating to the latest version of WonderCMS. Images that I previously could refer to by using just "/data/files/image.jpg" didn't show up. Instead the system tried to add "domain/page-name" to that automatically, so the full path would read "www.domain.com/page-name/data/files/image.jpg". Problem with this is that images don't get put into such subdirectories when uploaded. They appear in "data/files" as usual.

As an example I used this in my database file to specify unique backdrop images for each page for the parallax theme by using "background": "Image.jpg". I suppose I could create a new folder manually for each of my pages and upload the images there, but it seems like a complicated solution to something that is probably much simpler. So therefore I submit this as a bug report, in case this behaviour is unintended.

WonderCMS: 3.3.0
Theme: Parallax

**Comment by robiso** [comment]
Similar issue was reported here: https://www.wondercms.com/community/viewtopic.php?p=6061#p6061

Can you please try this change and see if it fixes the issue?
1. Open your index.php file and replace the whole parseurl() function.
Replace (starts on line 1970) 


```
	public function parseUrl(): string
	{
		$page = $_GET['page'] ?? null;

		if (!isset($page) || !$page) {
			$defaultPage = $this->get('config', 'defaultPage');
			$this->currentPageTree = explode('/', $defaultPage);
			return $defaultPage;
		}

		$this->currentPageTree = explode('/', rtrim($page, '/'));
		if ($page === $this->get('config', 'login')) {
			return htmlspecialchars($page, ENT_QUOTES);
		}

		$currentPage = end($this->currentPageTree);
		return $this->slugify($currentPage);
	}
```

and replace the whole function with:

```
	public function parseUrl(): string
	{
		if (!isset($_GET['page'])) {
			$defaultPage = $this->get('config', 'defaultPage');
			$this->currentPageTree = explode('/', $defaultPage);
			return $defaultPage;
		}

		$this->currentPageTree = explode('/', rtrim($_GET['page'], '/'));
		if ($_GET['page'] === $this->get('config', 'login')) {
			return htmlspecialchars($_GET['page'], ENT_QUOTES);
		}

		$currentPage = end($this->currentPageTree);
		return $this->slugify($currentPage);
	}
```

**Comment by Imerion** [comment]
Thanks again for really quick help!

1. Yes. I tried the Sky theme and the result is the same.
2. I tried changing this code but I'm afraid it didn't help.

**Comment by robiso** [comment]
@Imerion

1. Do you have these issues only on subpages?
2. You didn't have these issues in 3.1.0 and 3.2.0 - from which version did you update from?

**Comment by Imerion** [comment]
1. No, it's on the normal pages. The site has no subpages at all.
2. I updated from 3.1.4, which worked fine.

**Comment by Imerion** [comment]
Also, as mentioned in the forum post you linked, the problem doesn't appear on the start page, only on other pages. On the start page files are referenced from /data/files as before.

**Comment by robiso** [comment]
I'm trying to reproduce this issue was we speak.

Can you correct these steps if they are wrong?

1. Login to WCMS website.
2. Through the settings, upload an image.
3. Try linking to that image in a page (that is not homepage) with just "/data/files/image.jpg"?

Does this sound like the steps necessary to reproduce this?

**Comment by Imerion** [comment]
Yes, that sounds correct. As an example, I have the following code in my theme.php file to add a small mail-icon to the menu. Before the mail icon showed up, but now it doesn't. (Other than on the start page that is.)

<a href="mailto:mail@mail.com" class="nav-link">
  <img alt="Mail" src="data/files/Mail_icon.png" width=16" height="16">
</a>

**Comment by Imerion** [comment]
I could mail you the adress to the actual page if that would help.

**Comment by robiso** [comment]
@Imerion please do, you can do it to hi@wondercms.com, I'll be debugging this.

**Comment by robiso** [comment]
To make it easier, you can do a clean install and copy over the theme from your current website to the subfolder where you can check the 3.1.4 version.

**Comment by Imerion** [comment]
I also updated the summernote editor plugin, simple statistics plugin and additional contents plugin, as well as the theme, but that was after updating to WonderCMS 3.3.0. So the problem appeared before I updated anything else.

**Comment by robiso** [comment]
While inspecting your website, it seems the mailbox icon would be fixed by just adding a "/" in the path, example:
changing
`src="data/files/Mail_icon.png"`

to
`src="/data/files/Mail_icon.png"`.
as this is the correct path in relation to the domain.

Still not sure where the problem lies. Can you provide another example with other images?
I would be really interested to see how this worked on WonderCMS 3.1.4.

**Comment by Imerion** [comment]
Right, that part with the mail icon was easy. :)

Perhaps the problem is with how the parallax theme handles backgrounds then. Because in my database.js I have an entry like this for every page:

```
"page": {
  "title": "Page name",
  "keywords": "keywords",
  "description": "﻿Description",
  "content": "<p>Content here.<\/p>",
  "background": "image.jpg"
},
```
And here I can't really do:
```
"page": {
  "title": "Page name",
  "keywords": "keywords",
  "description": "﻿Description",
  "content": "<p>Content here.<\/p>",
  "background": "/data/files/image.jpg"
},
```
Because that results in the image pointing to: https://www.pagename.com/page/data/files//data/files/image.jpg

**Comment by robiso** [comment]
@Imerion is there any chance you could pack up the theme in a ZIP file and send it over?
I'd like to compare the 3.1.4 and 3.3.0 changes to see what went wrong and how this worked before.

**Comment by Imerion** [comment]
I have sent you archives with the theme before and after the update. I hope it helps. Sorry for all the trouble!

**Comment by robiso** [comment]
@Imerion can confirm I've received it and debugging this further.
Currently it does seem something in the index.php is affecting this. Will let you know back with some results.

Thanks for helping debug this, seems like we should be able to figure it out and push out a fix.

**Comment by robiso** [comment]
@Imerion found a fix you can apply immediately.
On line 2367, replace the line
`		$parentSlug .= $item->slug . '/';`
with
`		$parentSlug .= $item->slug;`

Will do some more testing to make sure subpages aren't broken, however this solved the issue you have.

**Comment by Imerion** [comment]
That solution worked, thanks!

As the site doesn't use subpages this will solve my problem for now. But tell me if I can help you any further with debugging, and again I thank you for taking your time with this!

**Comment by robiso** [comment]
@Imerion most welcome, this isn't a full blown solution just yet. Will update the thread.

You're welcome and likewise, thank you as well for helping debug this and sending over the files.

**Comment by robiso** [comment]
@Imerion got a solution that fixes all issues and supports subpages.

**Comment by Imerion** [comment]
Awesome! I can confirm it works fine here.

**Comment by robiso** [comment]
@Imerion thank you.
WodnerCMS 3.3.1 publishes and updates should be available with this fix for all WonderCMS users soon.

Glad to close this issue, feel free to repen it if necessary.
