### ISSUE TITLE
Fatal error when logging in

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms#255]
Please note that I'm getting the following error when I try to log in on **Windows**, **localhost**, **PHP 7.4.26**:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Wcms::moduleCacheMapper() must be an object, null given, called in C:\Wamp.NET\sites\merc\index.php on line 1278 and defined in C:\Wamp.NET\sites\merc\index.php:1291 
Stack trace: 
#0 C:\Wamp.NET\sites\merc\index.php(1278): Wcms->moduleCacheMapper(NULL) 
#1 C:\Wamp.NET\sites\merc\index.php(1350): Wcms->updateModulesCache() 
#2 C:\Wamp.NET\sites\merc\index.php(1244): Wcms->cacheModulesData() 
#3 C:\Wamp.NET\sites\merc\index.php(1194): Wcms->updateAndCacheModules() 
#4 C:\Wamp.NET\sites\merc\index.php(1785): Wcms->checkModulesCache() 
#5 C:\Wamp.NET\sites\merc\index.php(157): Wcms->notifyAction() 
#6 C:\Wamp.NET\sites\merc\index.php(15): Wcms->init() 
#7 {main} thrown in C:\Wamp.NET\sites\merc\index.php on line 1291
```

Basically, I can use the website fine, but when I enter the password to log in, I get the error.
**WonderCMS v3.3.1**

**Comment by robiso** [comment]
@Tangol hey and welcome.

1. Are you logged in after the error shows? And does the website work normally afterwards or is it broken?
2. Does the error occur on any other pages?

**Comment by Tangol** [comment]
@robiso to reproduce the issue:
1. Unzip the wondercms-331.zip in the web root
2. Try to log in with the provided password

Result: the entire install breaks and becomes unusable.
Video recording with the issue: https://drive.google.com/file/d/1wxiZXItgX8Dx2aHknjlgX-jgq8LubprD/view

Note that on the same localhost setup, in different folders, I also have a WordPress, a Bludit, and 2 other different scripts, and they all work perfectly.

**Comment by robiso** [comment]
@Tangol , we tried debugging and we could not reproduce it, since it seems there is something that your host is blocking in regards to fething the cache file.

We however added handling of this error, so you should be able to login normally, however the cache file will not be generated.

Please feel free to reopen this issue.
