### ISSUE TITLE
PHP Notice on v3.3.2

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms#266]
Please note that I'm getting lots of these notices on **PHP 7.4** and **Wonder 3.3.2**:

`PHP Notice:  Undefined index: menu in /home/public_html/index.php on line 2088`

**Comment by robiso** [comment]
@Tangol can you open your database.js file and paste only the whole menu array here?

Please be careful not to share the upper part of the config which includes "loginURL" and hashed "password".

**Comment by Tangol** [comment]
```
        "menuItems": {
            "0": {
                "name": "Home",
                "slug": "home",
                "visibility": "show",
                "subpages": {}
            }
        }
```
I just have 1 menu item - `Home`.

**Comment by robiso** [comment]
This will be fixed with the new version of WonderCMS (coming within the next few days).
@Tangol thank you!
