### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [robiso/wondercms#279]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by robiso** [comment]
Hi @codehangen, WonderCMS is still an active project (we are running strong on 15 years 🎉)

We're planning a release soon with some minor fixes and PHP 8+ compatibility upgrades. 

Did you have anything special in mind in terms of the already opened issues? 
- If you're familiar with jQuery, this has been on the users wish list for some time:
  - https://github.com/robiso/wondercms/issues/125
  - https://github.com/robiso/wondercms/issues/276

Really happy to see active contributors coming in!
