### ISSUE TITLE
Undefined index 'page'

### ISSUE THREAD

**Issue by halojoy** [robiso/wondercms#31]
Undefined index 'page' in line 92

Change to fix:
92 if (**isset($_GET['page'])** && $_GET['page'] == wCMS::get('config','login')) ........

**Comment by wdj-ac** [comment]
Thank you for this bug report. This will be fixed in a future release.

**Comment by robiso** [comment]
hello @halojoy thanks for reporting this - can you please additionally describe where this happens - Apache, NGINX, IIS, or some other configuration. Do you know what version of PHP you're running?
