### ISSUE TITLE
Vulernability in WonderCms

### ISSUE THREAD

**Issue by ZeroxCodeSec** [robiso/wondercms#36]
Hello
I found a vulnerability in wonder cms ,where i can report it?

Thanks

**Comment by wdj-ac** [comment]
Hi,
thank you for your help! The best way, will be a private message to wiz:
https://www.wondercms.com/forum/memberlist.php?mode=viewprofile&u=2

Regards

**Comment by robiso** [comment]
Hello Zerox, you can also send a message directly to info@wondercms.com ASAP.

**Comment by ZeroxCodeSec** [comment]
Hi.
I send it both(Private MSG , Email).
Please check it.

Zerox Security Lab
Good Luck/

**Comment by robiso** [comment]
Proper action has been taken, we've kindly asked @ZeroxCodeSec to re-test our unpublished patched version.

If everything is ok, we'll push out 2.1.1 today, with public credits to Zerox Security Lab for reporting this.

**Comment by robiso** [comment]
Zerox Security Lab has ensured us that the problem has been fixed.
We are in the process of pushing out version 2.2.0 with some additional fixes.
