### ISSUE TITLE
[Plugin request] Multi-language

### ISSUE THREAD

**Issue by AndiLeni** [robiso/wondercms#40]
Hello,
I wanted to know whether it would be possible to implement a language switcher for the admin interface.
A possible solution would be using i18njs. The work needed to realize this should not be that big because wCMS already relies on JSON database.
I'd love to hear your opinion.

**Comment by robiso** [comment]
I think this wouldn't be an easy mission, as almost everything in the settings panel is hardcoded in terms of words/description, except for the content.

I guess the easiest way would be to write a plugin, which overwrites settings function. This would require re-writing the whole settings function in the plugin and displaying it again.

**Comment by AndiLeni** [comment]
Unfortunately, I have to admit that my knowledge is not enough to tackle this project.  In my computer science studies I am still at the beginning. But I would help if it should come to an implementation.

**Comment by robiso** [comment]
I don't think that's a problem, we can add it to the "roadmap" and see if anyone wants to tackle this issue.

In the mean time, could you give this 2.3.2 (test version) index.php a drive?
https://github.com/robiso/WonderCMS-testRepo

**Comment by AndiLeni** [comment]
I tested the version and found no problems. No error messages and no problems during usage.

**Comment by robiso** [comment]
Thank you @AndiLeni. Preparing for 2.3.2 roll out in the upcoming days.

**Comment by PiersMorgan** [comment]
I believe i have come up for a solution to this using PHP.
The code will detect the language, validate it and then depending on the language redirect to the correct admin page, e.g /admin_es /admin_de 
etc

The PHP code is a few lines and i have placed it within the index.php for now, but can easily be ported to a plugin which when uploaded includes this piece of code.

**Comment by RarogCmex** [comment]
Language support must be an very good feature, I think. May be we should add an a category languages such as plugins/themes categories.

**Comment by StephanStanisic** [comment]
I'd vote for a solution that uses a plugin to supply language files. Have some special handling in the core, but let plugins "hook" language files to the core.

Something like:
```
plugins/
	language-nl_NL/
		nl_NL.csv
		language-nl_NL.php
```

And letting the plugin pass a dictionary of translations to the core.

**Comment by StephanStanisic** [comment]
Some time ago this maybe a bit tricky but plausible idea popped in my head. A lot of translations are in a `preg_replace` format. What if we just preg_replace the admin html?

So behold: here is a really simple solution to the translation issue.

Add a lot of `preg_replace`-style translations in a csv (most CMSes I've tried used this format, so that's why I did it too) and just looping over them. Thats it.

Here is a repo with the admin html translated to Dutch:
https://github.com/StephanStanisic/language-nl_NL

It isn't the nicest solution, but by prepending every preg_replace with the end of the tag, we assure that only the contents of the tag are replaced, and not other things.

More on how the csv is created in the README of the repo.

I still think that translations is something that should be the task of the CMS, and that plugins could deliver the language files. But this method gives us a easy solution for the time being.

**Comment by RarogCmex** [comment]
Experimental Russian translation based on yours. Currently I can't test it because my server is awaiting to bought ^), so I'll test it after another week or two.
https://github.com/RarogCmex/zlanguage-ru_RU

**Comment by StephanStanisic** [comment]
Looks awesome! I found some issues and have opened an PR!

**Comment by RarogCmex** [comment]
> Looks awesome! I found some issues and have opened an PR!
![image](https://user-images.githubusercontent.com/20739233/77182966-6f953980-6aef-11ea-86f4-36b1f49a1613.png)
Thank you, now I confirm it's works. There are some untransleted words however, but I'm not going to do it todays.
To do next, translate plugins such as simple blog.

**Comment by RarogCmex** [comment]
I've just updated https://github.com/RarogCmex/zlanguage-ru_RU with translating everything that I can

**Comment by robiso** [comment]
@StephanStanisic @RarogCmex 
I've prepared an updated version for the updated/upcoming WonderCMS release:
https://github.com/robiso/zlanguage-si_SL
- the above is a fully complete and fully working translation with all of the unnecessary things removed

Note: this probably wont fully work with your current versions, but in the upcoming 3.0.8 version it's the full thing.

Love your effort, thank you for creating this @StephanStanisic. Also thanks for your contribution @RarogCmex 🚀

**Comment by robiso** [comment]
Closing this issue (after 3 years) since we now have language plugins.
Thank you @StephanStanisic!
