### ISSUE TITLE
List of all requests / Roadmap

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#41]
- Old development thread can be found here: https://github.com/robiso/wondercms/issues/21
----
# User requests
### - All done!

# In progress or inactive
## Short guidelines for tackling any of the requests
1. The solution to the possible improvements should be compact/small/smart and clean in terms of code.
2. Awesome solutions are rewarded with a honourable mention on the official WonderCMS website - https://wondercms.com/special-contributors and the WonderCMS download page https://wondercms.com/latest.
 - If our donation fund isn't empty, we'll gladly reward you with a donation as a token of appreciation.

-----
## Finished improvements from previous roadmaps/requests
<del>1. Clean(er) URL's (short problem description: spaces and special characters URL handling + saving to database and displaying them in menu)
Long problem description and example:
When an user enters "my new page" in their menu at their example.com domain, spaces aren't stripped and the URL is example.com/my new page. The solution would be to replace spaces with the "**-**" character so the URL would be example.com/my-new-page.
1a. But what about all other special characters? And what "URL" are we going to save in the database in those cases.
1b. Once we update WonderCMS with this feature, how do we handle the user page names in their database.js to avoid an upgrading mess?
1c. After all this, we still need to display pages in the menu exactly the user entered them.
**EDIT**: this looks promising: http://cubiq.org/the-perfect-php-clean-url-generator
**IN WORK: @wdj-ac has started working on this, contribute if you can: https://github.com/wdj-ac/wondercms/issues/</del> - **DONE, thanks to @wdj-ac (Pascal Jordin)**

<del>2. Display all pages in the settings panel and additionally include some "hide from menu" functionality.
Problem: There's currently no "full list" of pages in the settings. A solution to this would be to view the database.js but that's definitely a hassle. We need a simple way to display all pages and a checkbox in the current page settings menu, that would enabe the user to hide the page from the menu.
**IN WORK: @wdj-ac has started working on this, contribute if you can: https://github.com/wdj-ac/wondercms/issues/</del>  - **DONE, thanks to @wdj-ac (Pascal Jordin)**

<del>3. Enable users to install plugins via the settings panel. **(Almost done, test version in near the end)**
  3a. This should be an input text field, which would take a ZIP link (allowed only from github.com domain) and extract it to the users plugin folder.
  3b. Enable users to update their plugin with a new ZIP link (if the plugin name is the same).
  3c. Simple plugin list (list all plugins from plugins folder)
  3d. Enable users to easily remove a plugin (from the plugin list, a small "X" would do and a confirm dialog).
  3e. Same functionality for themes (we will probably need an extra field for this, possibly a check box to choose between installing a plugin or a theme to avoid two text fields).</del>
  
### <del>Add special section on WonderCMS website for plugins and themes</del>
<del>Automate the process of reading themes/plugins from GitHub and display them on the WonderCMS website in a searchable and paginated way (numbered pages) possibly searchable by name).</del> - will be partially provided with upcoming 3.0.0 release
### <del>[Plugin request] Multi language settings panel (development discussion: https://github.com/robiso/wondercms/issues/40)</del>

**Comment by robiso** [comment]
Adding new plugin request.

**Comment by camillo777** [comment]
Maybe a website refresh?

**Comment by robiso** [comment]
@camillo777 done 🚀 
Revamped: https://www.wondercms.com/

Any feedback is appreciated.

**Comment by camillo777** [comment]
@robiso really awesome!
