### ISSUE TITLE
[Plugin request] Insert PHP code on any page

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#43]
### [Plugin request] Insert PHP code
- Enable users to enter PHP code on any page via the editable areas or a new field generated by the plugin.

**Comment by PiersMorgan** [comment]
I think this may be possible with an edit to Summer note's code, i am unsure about implementation into the default editable blocks though, but then again i am using summer-note plugin and have not checked. I will disable summer-note and see what i can come up with for implementing this feature into the default blocks.
