### ISSUE TITLE
local nginx port - howto prevent it in links?

### ISSUE THREAD

**Issue by katakombi** [robiso/wondercms#47]
Hi there, I want to run wondercms using nginx on a local port 8080.
Port-forwarding is changing this port to std 80 again. But when I access index.php all links appear to be like this:

www.mycomain.com:8080:relative/link.html.

howto prevent wondercms to be using this port configured in my web server?

thx
Stefan

**Comment by robiso** [comment]
Hello @katakombi. 

Please answer a couple of questions so we can help you better.
1. Have you edited your nginx.conf for WonderCMS as instructed in the wiki?
2. Can you provide a better example of a link, it is impossible for WonderCMS to generate an .html extension 
- is the link similar to mydomain.com:8080/wondercmsPATH/index.php?page=example
- does the link contain the word relative?
- can you possibly copy/paste the whole URL?
3. Does any page load correctly, are you getting any error messages?
4, Did any other app correctly forward the port, or is it just WonderCMS that doesn't do this correctly?

I'm not an NGINX expert, but WonderCMS should work with any port out of the box. I've done some Googling and found some examples on how to achieve this with the nginx.conf (and WonderCMS should listen to the config by default).
https://stackoverflow.com/questions/37999926/unable-to-forward-port-80-to-8080-using-nginx
https://serverfault.com/questions/536576/nginx-how-do-i-forward-a-http-request-to-another-port

Answer the questions and I'll try to help you to the best of my power. :+1:

**Comment by katakombi** [comment]
Hi @robiso  thanks very much for helping out. 
I am pretty much aware it is most likely an nginx thing and got maybe nothing to do with wondercms.
My page is hosted right now here http://dolmades.org/index.php but just for the time being since it is unprotected :)
If you hover over the login link you'll see it resolves to http://dolmades.org:8080/loginURL

My current nginx config is:

site config
server {
    listen       8080;
    server_name  dolmades.org;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    root   /var/www/html;
    index  index.php index.html index.htm;

    location ~ database.js {
        return 403;
    }

    autoindex off;


    location / {
        if (!-e $request_filename) {
            rewrite_log on;
            rewrite ^/(.+)$ /index.php?page=$1 last;
        }
    }

    # pass the PHP scripts to FastCGI server listening on socket /run/php/php7.0-fpm.sock
    #
    location ~ \.php$ {
        #fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass   unix:/var/run/php/php7.0-fpm.sock;
        #fastcgi_index  index.php;
        include        snippets/fastcgi-php.conf;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny  all;
    }
}

global conf

user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
	rewrite_log on;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}

php conf

dolmades.org/info.php

**Comment by robiso** [comment]
Don't thank me just yet, hope we can get this up and running.

_How does it get that port info? Can it be overridden?_
- the code that displays the URL (along with http or https and some other minor checks) - this is located in index.php, line 117 to line 119, called the url function. Yes it can be overwritten (but like you probably know, you would have to re-enter this change with each update, since we overwrite index.php with each update.
```
public static function url($location = '') {
	return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'] . ((($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443'))? '' : ':' . $_SERVER['SERVER_PORT']) . ((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) . '/' . $location;
}
```
You could change the function to not read the port automatically, something like this:
```
public static function url($location = '') {
	return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'] . ((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) . '/' . $location;
}
```
The above will probably produce the wanted results, but I really wish it could be as simple as changing it like this in your server config (https://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash).

Here's the discussion when we implemented the above code for any port support:
https://github.com/robiso/wondercms/pull/37

// Edit
You can also try:
public static function url($location = '') {
	return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'] . ((($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443') || ($_SERVER['SERVER_PORT'] == '8080')) ? '' : ':' . $_SERVER['SERVER_PORT']) . ((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) . '/' . $location;
}
```

Let me know how this goes, I'll try to see and think of a simple plugin, that would enable you to overwrite the url function without having to do it all over with each update.

**Comment by katakombi** [comment]
I see.. 
thanks for hinting to the pull request. I most cases this makes perfectly sense, but I intend to run nginx+php-fpm and wondercms in user space containers using a generic config across different systems. Ports are forwarded through a router behind.
In this case it doesn't so useful to obtain the domain name and the port number from the settings of the local nginx. I guess the best would be to have in the 'settings' a checkbox 'autodetect external urls'  and two fields 'domain-name' and 'port-number' for manually overriding the functions once you uncheck this option.

I tried to fiddle around with nginx proxy settings but they do not seem to have effect on the existing php code.
Next I'll go a try to rewrite the php function...

**Comment by katakombi** [comment]
I've patched index.php.

What it does is to allow to set `servername, serverport, serverdir` statically in `database.js` and override the dynamic detection. Since it is static it won't help in all cases but it seems that the `_SERVER` variable has a lot of other content which could possibly made use of to contain the correct remote port or host name.
I just don't know how to configure that in nginx nor do I know if it would be consistent across web servers (nginx, apache...).
This works for me, however, so, please tell me what you think of this solution?
Could you include it in wondercms?

```
index.php.diff                                                                                                                                                                                            100% 2216     2.2KB/s   00:00    
stefan@khaleesi ~ $ cat index.php.diff 
--- /var/www/html/index.php.backup	2017-10-29 08:14:47.567281032 +0000
+++ /var/www/html/index.php	2017-10-29 10:57:11.346750293 +0000
@@ -115,7 +115,14 @@
 		return wCMS::url('themes/' . wCMS::get('config','theme') . '/' . $location);
 	}
 	public static function url($location = '') {
-		return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'] . ((($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443'))? '' : ':' . $_SERVER['SERVER_PORT']) . ((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) . '/' . $location;
+		if (wCMS::get("config","useDynamicServerSettings")) {
+			return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'] . ((($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443'))? '' : ':' . $_SERVER['SERVER_PORT']) . ((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) . '/' . $location;
+		} else {
+			$_servername = wCMS::get("config","servername")? wCMS::get("config","servername") : $_SERVER['SERVER_NAME'];
+			$_serverport = wCMS::get("config","serverport")? wCMS::get("config","serverport") : $_SERVER['SERVER_PORT'];
+			$_serverdir  = wCMS::get("config","serverdir")?  wCMS::get("config","serverdir")  : dirname($_SERVER['SERVER_SCRIPTNAME']);
+			return 'http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_servername . ":" . $_serverport . $_serverdir . '/' . $location;
+		}
 	}
 	public static function parseUrl() {
 		if (isset($_GET['page']) && $_GET['page'] == wCMS::get('config','login')) return htmlspecialchars($_GET['page'], ENT_QUOTES);
@@ -553,6 +560,10 @@
 				'theme' => 'default',
 				'defaultPage' => 'home',
 				'login' => 'loginURL',
+				'useDynamicServerSettings' => true,
+				'servername' => $_SERVER['SERVER_NAME'],
+				'serverport' => $_SERVER['SERVER_PORT'],
+				'serverdir' => dirname($_SERVER['SERVER_SCRIPTNAME']),
 				'password' => password_hash('admin', PASSWORD_DEFAULT),
 				'menuItems' => [
 					'0' => [
@@ -607,4 +618,4 @@
 		]);
 	}
 }
-wCMS::init();
\ No newline at end of file
+wCMS::init();
```

**Comment by robiso** [comment]
Tested out your solution on main domain, subdomain, subdomain + dir and all worked perfectly fine.
Even when the first run of WonderCMS (first visit generates the database.js) saved the 80 port in the database, I had no trouble visiting the 443 port. Additionally tested out scenario where I set it to false, and everything worked out well.

I personally like the idea that the user could manually set this the dynamic value to false in the database.js itself.

Can I kindly ask for your input @gakowalski and @Alamantus? Does anyone notice any downsides to this?
@katakombi, can you please provide your name/last name and possibly a website, so we can include you to our list of contributors if this gets included?
Note: @katakombi, no matter how hard we try to remove the last line from GitHub, it will always re-appear, the extra space is never included in the ZIP file, only on GitHub files. :smile:

**Comment by Alamantus** [comment]
Those code changes look pretty good to me! If you don’t have an issue with adding those lines to the code base, I think it would be good to include the option for power users.

The only problem I can foresee is that adding those lines could potentially become an issue if a non-advanced user wanted to move their website to a new host and someone else had previously updated those settings to a specific server beforehand. It could cause some confusion/frustration if the user doesn’t know that extra settings were tweaked in the `js` file.

Maybe we could include the code change to the `url()` method but not update the default config? We could include _how_ to change the `database.js` to make it utilize the advanced feature in the wiki or something, but it would not add the current server’s data by default. That way, a user could make the change but have a reference for what changed if they looked it up in the future.

Does that make sense? Thoughts?

**Comment by katakombi** [comment]
Hi everyone, 
 one thing is that the port will be always included when the static config is taken. this could be changed in similar ways like the dynamic config removes std ports (80, when http, 443 when https is being used).
Personally I don't care to have ports in the generated links, but I wanted to let you know!
I'd be happy if you could merge the code, my name is Stefan Kombrink.

@Alamantus I am not sure I understand your concern/proposal. My standard config is not changing any behaviour in comparison as it was before. The admin needs to manually switch the dynamic config off. Could you elaborate more, please?

**Comment by Alamantus** [comment]
@katakombi My concern is if someone uses WonderCMS to build a website for a user, then leaves, then the user wants a new web host. WonderCMS is great because you can simply take all the files in the folder and put it on any other web host and it will act exactly the same. If there had been an admin who utilizes the feature and then suddenly there is no longer an admin, the user could have a frustrating time trying to figure out what's wrong with their website if it is not clearly documented as an extra thing.

Or, imagine this (perhaps unlikely) scenario

This code sets the defaults to the _current_ server:

```
'servername' => $_SERVER['SERVER_NAME'],
'serverport' => $_SERVER['SERVER_PORT'],
'serverdir' => dirname($_SERVER['SCRIPT_NAME']),
```

If `'useDynamicServerSettings' => true,` ever somehow (accidentally, perhaps?) gets set to false and then the user moves the site to a new server. Those default settings are still pointing to the old `servername`, `serverport`, and `serverdir`, so when the user puts the site on their new web host server, their links are all broken because they are pointing to the previous server.

What I'm suggesting is to not set those default settings within the initialization code, but rather to include instructions for how to set the JSON in the resulting `database.js` file only if necessary.

Does that make sense?

**Comment by katakombi** [comment]
@Alamantus You vote for rather having no init code for the `database.js` than to have it broken when a common user move it. I understand this problem but I don't understand how you want to store the settings then? How do you want to set the json in the resulting `database.js` file only if necessary, and how would it avoid the very same problem? 
Or do you want to outsource the url function?

**Comment by gakowalski** [comment]
I believe the proposed changes lead in the wrong direction. WonderCMS is a CMS system and should only minimally deal with issues such as ports, addresses, redirects, proxies - it should focus on content management. If not for the fact that it currently uses absolute URLs (which is an anti-pattern generating exactly this kind of problems we are discussing right now), it should not deal with them at all. The right place for such things is the web server and the router. Nginx has a wide range of configuration options and proper redirections and rewrites can be achieved in a variety of ways. WonderCMS in this aspect should strive to *simplify* the code and not *expand* it.

You might think that it's not a big deal to add a couple new settings to `database.js`, defining static server names or ports, but power users might need more: setting different protocols, specific HTTP headers etc. All these things are currently supported in web servers. There is no need to duplicate such features and solve complexities that it might bring. It has been successfully addressed elsewhere.

What *eventually* could be implemented in WonderCMS is proper support of proxy specific variables like `HTTP_X_FORWARDED_SERVER`, `HTTP_X_FORWARDED_HOST`, `HTTP_X_FORWARDED_PROTO`, `HTTP_X_FORWARDED_PORT ` and others. This could make configuring web servers easier.

@katakombi 
> I've read about nginx config (forgot to bookmark the page) that SERVER['SERVER_PORT'] is defined by the running web server and cannot be overridden by the user.

You can set it's value using [fastcgi_param](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/) in nginx config. You can aslo modify it in PHP script as regular variable, so there is no need to introduce additional variables and change body of `url()` . In your specific case, you might want to [hardcode SERVER_PORT value as 80](https://serverfault.com/questions/256191/getting-correct-server-port-to-php-fpm-through-nginx-and-varnish). If for some reason that wouldn't work, there are other ways like using [sub_filter module](http://nginx.org/en/docs/http/ngx_http_sub_module.html) to rewrite URLs in HTML content.

**Comment by katakombi** [comment]
I will try to modify SERVER_PORT once more based on what Grzegorz
recommends - I will prefer any solution which works without modifying
wondercms code.
I think it could help users a lot to have a hint in the installation docs
as to how the url function will determine links, and what to configure in
cases like mine. I'd say it is not such a special case...

**Comment by robiso** [comment]
@Alamantus, @gakowalski, @katakombi, thank you for the discussion and finding the time to contribute to this project.

@katakombi, did your SERVER_PORT solution work without editing the index.php? If you managed to do this without the edit (maybe using functions.php?), please provide your example so we can add it to the wiki.

So in short, what I need to be adding to the wiki:
- how the url functions works / how/where the links are generated
- working example for when a case like yours happens
- please suggest anything that might have helped you and you wish we already had in the docs (but had to find out the hard way)

Offtopic:
Once we gain more _ground_, anybody up for a WonderCMS summit in 2020? :tada:

**Comment by katakombi** [comment]
Dear @robiso your'e welcome. 
Please have a look at https://github.com/katakombi/wondercms/tree/nginx-docker where I forked wondercms and added a Dockerfile plus the related nginx/php configs.

This builds a container which hosts a wondercms in user space under port 8080.
For that docker needs to share the wondercms location under /var/www/html.
What users need to have is in particular the proper 
https://github.com/katakombi/wondercms/tree/nginx-docker/fastcgi.conf
and https://github.com/katakombi/wondercms/tree/default

**Comment by gakowalski** [comment]
@katakombi, I see the changes introduced in [fastcgi.conf](https://github.com/katakombi/wondercms/blob/nginx-docker/cfg/fastcgi.conf).
```
fastcgi_param  SERVER_PORT 80;
fastcgi_param  SERVER_NAME "dolmades.org";
```
However, I do not know what important changes you made to [default](https://github.com/katakombi/wondercms/blob/nginx-docker/cfg/default). Could you explain? My attention was caught only by `include snippets/fastcgi-php.conf;`. Is it a copy of `cfg/fastcgi.conf`? [Dockerfile](https://github.com/katakombi/wondercms/blob/nginx-docker/Dockerfile) contains command to copy that file but to `etc/nginx`, not to `snippets`.

**Comment by katakombi** [comment]
Yeah sorry, I've slipped that file which is part of the debian default installation:

```
root@f4a77c2004a6:/# cat /etc/nginx/snippets/fastcgi-php.conf 
# regex to split $uri to $fastcgi_script_name and $fastcgi_path
fastcgi_split_path_info ^(.+\.php)(/.+)$;

# Check that the PHP script exists before passing it
try_files $fastcgi_script_name =404;

# Bypass the fact that try_files resets $fastcgi_path_info
# see: http://trac.nginx.org/nginx/ticket/321
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;

fastcgi_index index.php;
include fastcgi.conf;
```

Maybe it would work without it just using the /etc/nginx/fastcgi.conf I'd need more testing to be sure.
Meanwhile you can track changes to my repo https://github.com/katakombi/wondercms/ as I plan to add https support in the nginx-docker branch and this will require more changes.

keep up the good work
Stefan

**Comment by robiso** [comment]
@katakombi, is there any way you could do a short explanation of how you've achieved wanted results? I'd love to include it in the wiki.

Please feel to re-open the issue if you feel it hasn't been properly solved.

**Comment by katakombi** [comment]
Hi @robiso 

 have a look at the Docker file here https://github.com/katakombi/wondercms/blob/nginx-docker/Dockerfile
It makes use of the following config files: 
https://github.com/katakombi/wondercms/tree/nginx-docker/cfg
You should  compare those to the default template configs which are delivered by the installed packages - the changes should be rather small.
It all boils down to override the PHP variables SERVER_NAME and SERVER_PORT.
Note that the configs are for HTTP not HTTPS.

Greetings and best wishes for 2018
Stefan
