### ISSUE TITLE
Trumbowyg editor

### ISSUE THREAD

**Issue by nibreh** [robiso/wondercms#5]
It would be nice with this editor:
https://alex-d.github.io/Trumbowyg/

What do you think about ?

**Comment by 1Seann** [comment]
I do like this editor so its a +1 from me. I do hope this gets added.

**Comment by nibreh** [comment]
It's simple to add Trumbowyg in a simple cms, but unfortunately, code of wondercms seems special. I would like to use markdown too. but I can't figure out how to use in wondercms. If you know someone who is best than me ... cheers

**Comment by anolis** [comment]
+1 here too

**Comment by robiso** [comment]
Or something like: http://nicedit.com/

We have to find a way to have a nice editor as a plugin, which would also base64 encode images, making it easier of not having to upload them to a specific directory.

I would also love to see if someone developed something like this. Any takers?

**Comment by spencerthayer** [comment]
Trumbowyg is nicer than nicedit.

**Comment by yassineaddi** [comment]
@spencerthayer I agree, it'll be provided as a plugin after releasing the stable version.

**Comment by robiso** [comment]
WonderCMS 1.0.0 stable is now released, along with it, Trumbowyg is now available as a standalone plugin. You can get in from the forum [over here](https://wondercms.com/forum/viewforum.php?f=30).

I'm marking this as closed, any issues with the editor from now on should be addressed at the plugins repository [over here](https://github.com/robiso/wondercms-plugins). Special thanks to Yassine Addi for making this possible.
