### ISSUE TITLE
HTML Validation Errors

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms#50]
Please note that I've found some errors during HTML Validation:
https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fwww.wondercms.com%2Fdemo%2F

PS: A simple CMS such as WonderCMS, should get a PERFECT score in all areas. :grinning:
https://gtmetrix.com/reports/www.wondercms.com/9VivHY2V
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.wondercms.com%2Fdemo%2F&tab=mobile

**Comment by robiso** [comment]
Please try it out on your own server (without plugins, as they are causing this, we're not the author of the plugins), and you will see
"Document checking completed. No errors or warnings to show." :)
- as it should be. :+1:
