### ISSUE TITLE
[Plugin request] Different Theme for each page

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms#51]
Right now, the system limits us in having the same layout on every page we create, and that kinda defeats the purpose of having the ability to add multiple pages, as these will all look the same.

**It would be great if we could assign a different theme to each page.**

For example, a developer could create a theme for the Homepage, and different themes for the other pages.
By default, each page would be created using the the main layout, which can be changed in the settings.
![theme](https://user-images.githubusercontent.com/3336728/33267274-7dfc1d20-d381-11e7-9532-1458cb3c8844.png)

**Comment by robiso** [comment]
I think this could be solved as a plugin, any takers? :)

**Comment by Tangol** [comment]
@robiso This is a must-have for WonderCMS, so it should be perfectly executed.
That's why we all agree that you are the most qualified person to do it. :grin:

Thanks!

**Comment by robiso** [comment]
I don't this I'll be attending this one, as even I personally use other CMS solutions for cases/customers like this. This could be also solved in numerous other ways, not by bloating-up WonderCMS.

If you find the **will** to do it, you're more than welcome to implement this feature, I'm sure someone will help if you get stuck at any stage. :)

**Comment by Tangol** [comment]
In order to successfully spread the word and attract more users and developers, you have to have more **features** available to the CMS itself.
Basically this is the starting point.
And as you mentioned, a plugin is a safe way to add these features (and by no means a plugin is to be considered bloatware!).

Sending people to other CMS platforms, to do different things, means losing them...
That's why WonderCMS didn't get much traction in the first place. 
I can guarantee that if you leave the **Roadmap** as it is, in 1 year from now, you'll find it the same, with 0 tasks accomplished.

And to get back to the topic, I have the will to do it, but unfortunately my PHP experience is very limited :disappointed:

**Comment by robiso** [comment]
Looks like somebody hasn't checked out the what's new log for the past 12 months, hard to do any guarantees at that stage. :laughing: 

WonderCMS isn't and can't be perfect for everybody (as we have seen in both the past and present). **That being said, I think you might have missed the point of WonderCMS. It's not meant to be a competitor to other solutions, but an alternative.** I have no problem reverting to other CMS solutions myself, nor do I have a problem suggesting other solutions to users. Sometimes one CMS will do, sometimes another.

That being said, I personally think we're definitely going in the right direction and supporters like CSS inventor Hakon Wium Lie (using WonderCMS: http://www.wiumlie.no/) affirm this. Fun fact: we're the only CMS listed next to WordPress on Microsofts Azure services: https://azure.microsoft.com/en-gb/try/app-service/web/express/?Step=template&language=php talking about traction? :smile: 

If you feel you could take this project into something else/higher state, I also fully support WonderCMS forks. :) Last but not least, do find the time to learn some more PHP, it will do you great and possibly even this project. :+1:  Still appreciate the comments/feedback!

To stay on the topic, **I'm looking forward to someone going after this plugin request.**

**Comment by PiersMorgan** [comment]
Having numerous themes per page sort of defeats the object of a theme for me, since a theme is supposed to flow throughout the site. I think what you are more hinting at is page layouts, for instance a sidebar and main column on one page, and 3 columns no sidebar on another. In my personal opinion this can be done but would require an entire rework since the CMS only uses a single theme.php and does not have separate pages such as, home.php, about.php, contact.php.

**Comment by robiso** [comment]
I couldn't agree more.

This should be a low priority plugin request. I personally won't bothered if this plugin doesn't get created - but if someone does create it in the long-term future, they can share it so others can use it.

**Comment by robiso** [comment]
Closing this "feature request", will re-open if there is enough interest.
