### ISSUE TITLE
After Upgrade to 2.4.0 Custom Login-URL not worked - Apache, Centos 7.4, Plesk, PHP 7.1

### ISSUE THREAD

**Issue by AlexL777** [robiso/wondercms#53]
Hi Developers,

Can you help me maybe. After the last WonderCMS upgrade, my custom login URL will stop working.

A blank page is displayed and the password entry field is no longer displayed.

I have the CMS under Centos 7.4, in Apache, Plesk, on a subdomain.

What else can I do to remedy this?

Thanks in Advance.

**Comment by robiso** [comment]
Seems like you might have forgotten updating plugins with the 2.4.0 update. Additional contents plugin is probably causing this error. Solution below (plugin link updates were included in the release notes: https://www.wondercms.com/whatsnew)

### 2 plugins need manual updating (copy/paste link)

    NOTE 1: If you don't have these plugins, there is no need to update them.
    NOTE 2: Always update WonderCMS before updating plugins.

1. Update link for Summernote editor plugin
- Copy the link below and paste it in your Settings->Themes & plugins, select "Plugin" and click update.
- https://github.com/robiso/wondercms-plugins/releases/download/summernote-2.4/summernote.zip

2. Update for Additonal contents plugin
- Copy the link below and paste it in your Settings->Themes & plugins, select "Plugin" and click update.
- https://github.com/robiso/wondercms-plugins/releases/download/additional-contents-2.4/addition_contents.zip

**If you cannot access your website**, you can unzip these plugins via FTP or a file manager.

**Comment by AlexL777** [comment]
Thanks for the quick Help. My Problem is solved 👍

**Comment by robiso** [comment]
No problem, to an awesome 2018!
> Closing issue.
