### ISSUE TITLE
Show Contact Form only on one Page - how does it work?

### ISSUE THREAD

**Issue by AlexL777** [robiso/wondercms#54]
Hi Developers,

How can I display the contact form on a single page? I can paste the PHP code into theme.php, but the form will be displayed on all content pages.

For the contact I have a page "contact" and only there should the form be displayed.

How can I relay it?

Thanks in Advance.

**Comment by robiso** [comment]
These are the instructions as shown on the plugin page: https://github.com/robiso/wondercms-plugins/releases/tag/contact-form

To recap, here's the solution for showing the contact form only on the page called contact.
Make sure to replace the below with your real email.

## How to show form on a specific page
```
<?php if (wCMS::$currentPage == 'contact'): ?>
	<?php
		global $contact_form_email;
		$contact_form_email = "your.email@example.com";
	?>

	<div class="container marginTop20">
		<div class="col-xs-12 col-md-6 col-md-offset-3">
			<div id="contactform" class="grayFont" style="height: 265px;">
         		  	<?php contact_form(); ?>
			</div>
		</div>
	</div>
<?php endif ?>
```

**Comment by AlexL777** [comment]
Thanks for this solution. It was a success. That's how I could realize it 👍

**Comment by robiso** [comment]
Glad to help. :+1: 
> Closing issue
