### ISSUE TITLE
[VOTE] Choose between 4 WonderCMS designs

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#58]
### 1 (black ribbon)
![image](https://user-images.githubusercontent.com/6200139/36497909-04d3d226-173d-11e8-818e-83c729a6a303.png)

### 2 (purple ribbon)
![image](https://user-images.githubusercontent.com/6200139/36497929-13fbad46-173d-11e8-82fc-59fcbc95d4ed.png)

### 3 (black ribbon with space/astronaut background)
![image](https://user-images.githubusercontent.com/6200139/36497943-1be592ec-173d-11e8-9f01-4a831b6d8426.png)

### 4 (purple ribbon with space/astronaut background)
![wcms-4](https://user-images.githubusercontent.com/6200139/36500227-040a4616-1744-11e8-962c-f64ecb163be9.jpg)

**Comment by tunguskha** [comment]
3 !

**Comment by robiso** [comment]
# Current vote status
Votes from the [WonderCMS community vote topic](https://www.wondercms.com/forum/viewtopic.php?f=17&t=1044) are included.


### Design 1
- 0 votes

### Design 2
- 1 votes

### Design 3
- 3 votes

### Design 4
- 0 votes

**Comment by PiersMorgan** [comment]
Would you be interested in me coding you a custom site? It will look amazing and have download sections for each plugin/theme with the versions and all that good stuff.

**Comment by robiso** [comment]
@PiersMorgan I don't this as a priority, otherwise absolutely :+1: .

Not meaning any harm, I suggest not getting too much on your plate (as you already have #52 and upgrading social blocks so they wouldn't need editing of the theme.php // adding value with user friendliess).

The website would have to meet multiple conditions (that are currently met):
- websire has to run on WonderCMS (it would funny/ironic to be running such a project and not using it:)
- important: the index.php must not be modified, so the website is upgradeable with new versions of WonderCMS (as you probably know, each update overwrites the index.php)
  - check the wiki/docs, as modiifications are possible with a simple functions.php inside the theme folder, or using a custom plugin
- if you decide to do this in the future, we'll put another contest up or just add it to the existing ones, so people can choose their favorite

In the mean time, what's your favorite of the above 4 pictures? :smile: If you already voted in the community, no need to re-cast your vote.

**Comment by PiersMorgan** [comment]
#3 
And social blocks did work originally without editing of the theme.php but it required functions.php which must be manually created before being hooked in so it is not possible to some extent.

**Comment by robiso** [comment]
Any chance you could publish the original one that doesn't need editing?

**Comment by PiersMorgan** [comment]
I do not have it but i can recode it i am sure. I overrided the old one with the new one.

**Comment by northivanastan** [comment]
Design 3, with certainty.
