### ISSUE TITLE
The web site does not filter special characters, resulting in XSS

### ISSUE THREAD

**Issue by thatqier** [robiso/wondercms#59]
The web site does not filter special characters, resulting in XSS

URL：https://www.wondercms.com/demo/

![tim 20180228172025](https://user-images.githubusercontent.com/11780881/36779802-263d3082-1cac-11e8-8bfb-c07f208a6bb9.png)

**Comment by robiso** [comment]
This has been reported multiple times, please check #57.

It might make sense for us to filter the demo, but doesn't make sense to take out executing JavaScript anywhere in WonderCMS, as it's been a feature since 2008.

Closing issue, feel free to re-open.
