### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by budmc29** [robiso/wondercms#60]
VIsit https://www.wondercms.com/demo/

You will get this error:

> The page isn't redirecting properly
> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
> This problem can sometimes be caused by disabling or refusing to accept cookies.

Visit any other page after that, and you will see this notification:

![screenshot-2018-3-3 wondercms - one of the smallest flat file cms - home 1](https://user-images.githubusercontent.com/7063792/36934015-90cb302c-1eda-11e8-95dd-b917034d925a.png)

OS: Ubuntu 14.04
Browser: Firefox Quantum

**Comment by robiso** [comment]
@budmc29 thanks for reporting. I manually reset the demo a sec ago.

This happens when there are numerous users trying to save data on the demo and the database.js gets corrupted. WonderCMS is meant to be a single user CMS, so not sure how we'd go by to prevent this sort of issue.

**Comment by budmc29** [comment]
Okay, thanks.

I don't have any idea, but when I wanted to see the demo I was only interested in seeing how to use the website, and how the UI looked like, not really saving anything.
But I might be in minority.

Another option would be some sort of file locking, I would say that it's better for some users to get an error if a situation that might corrupt the data will happen, than nobody being able to use the demo at all?

**Comment by robiso** [comment]
Your feedback/report is very much appreciated and I couldn't agree more. Not in any way saying this is your or the users fault, it's something that WonderCMS doesn't support and I haven't figured out how to prevent this in the demo yet, possibly with a solution explained below.

The demo is set to reset every 10 minutes, but there seems to be a glitch that prevents it from being reset when there are many users saving to the database (although WonderCMS is a single user CMS :).

I've moved the demo reset code check to run first, let's see if this solves it. Will keep an eye on the demo.

**Comment by robiso** [comment]
Just tested the above solution with a "corrupted" database. If it's stuck in a loop like you reported, the demo now successfully resets.

Thanks again for reporting @budmc29! :beer:
