### ISSUE TITLE
Plugin adding issue

### ISSUE THREAD

**Issue by Jeremy1980** [robiso/wondercms#62]
Contact form is unusable when you not skilled with PHP language.
When i change, theme, then loose my extended functionality, like above.

**Comment by robiso** [comment]
@Jeremy1980, this seems to be a plugin issue and not a WonderCMS core issue.

I suggest you open an issue with the plugin author if you dislike that it requires editing of the theme.php file: https://github.com/Hermadme/contact_form

This is one of the only plugins that requires editing the theme.php file (with instructions provided on the plugin page: https://github.com/robiso/wondercms-plugins/releases/tag/contact-form-2.4), this it can't work by simply changing the theme.

The plugin has know where you want to insert the contact form, this is why editing of theme.php is required (no PHP knowledge needed, just follow the simple steps provided with the plugin: https://github.com/robiso/wondercms-plugins/releases/tag/contact-form-2.4).

Closing issue, feel free to comment again to keep the discussion going.
