### ISSUE TITLE
Page availability

### ISSUE THREAD

**Issue by Jeremy1980** [robiso/wondercms#63]
When you change page visibility in GENERAL tab of settings window. User still can access this page via full known url. I recommend redirecting to 404 error page.

**Comment by robiso** [comment]
This has always been an intended feature (hiding pages only from menu).
Please check previous discussions:
https://www.wondercms.com/forum/viewtopic.php?f=17&t=1055&hilit=menu+hide
Also included it in the documentation:
https://github.com/robiso/wondercms/wiki/Hide-page-from-menu

If you feel like we should change the logic of how this works, please open a poll in the WonderCMS community. Closing issue, feel free to comment to keep the discussion going.
