### ISSUE TITLE
[Feature request] wCMS::menu() not suited to Bootstrap 4

### ISSUE THREAD

**Issue by northivanastan** [robiso/wondercms#71]
The current WonderCMS seems prohibitive to themes made with Bootstrap 4, since the theme function wCMS::menu() returns an unordered list. When attempting to use wCMS with a Bootstrap 4 theme, I found no items in the navigation menu (though they were present in the settings menu). This is because Bootstrap 4 seems to require "navbar-item" classes on the `<li>` tags in the menu and "navbar-link" classes on the `<a>` tags in the menu.

Thanks for your attention.

**Comment by robiso** [comment]
@northivanastan closing issue as this is implemented in the future upcoming version.
Please feel free to re-open this discussion if you have any questions.
