### ISSUE TITLE
Add support for PHP built in server

### ISSUE THREAD

**Issue by jellehak** [robiso/wondercms#75]
I am missing support for the PHP built in server. This gives a nice and quick way of getting started locally. Perhaps this could be included in the source or somewhere stated in the documents? Besides great project !

# How to

Add a file called router.php:
```
<?php

if(pathinfo($_SERVER["REQUEST_URI"], PATHINFO_EXTENSION)) {
    // asset file; serve from filesystem
    return false;   
} else {
    $_GET['page'] = parse_url($_SERVER["REQUEST_URI"])['path'];
    include 'index.php';
}
```

And run:
```php -S localhost:8090 router.php```

For proper logout:
Modify ```'logout&token='``` to ```'logout?token='``` in the index.php

**Comment by robiso** [comment]
Thank you @jellehak!

This has been added to the docs: https://github.com/robiso/wondercms/wiki/PHP-built-in-server.
I added an additional note: the logout link will have to be updated in index.php each time you update your WonderCMS.

As we reward all contributions with an honorable mention on the https://wondercms.com/special-contributors page, I'd like to ask for your first/last name and a website/twitter link, so you too can be added.

Closing issue, comment back with the data required to list you on the special contributors page if you don't mind being on it. Thanks again for contributing.
