### ISSUE TITLE
Separate Site & Config files

### ISSUE THREAD

**Issue by damon-kronski** [robiso/wondercms#8]
You cant name your sites "menu", "description", etc. because the files are in the same location as the config files...

**Comment by yassineaddi** [comment]
I agree, here is a workaround.
**index.php**
Replace this line
`$fval = @file_get_contents('files/'.$key);`
With
`
if(in_array($key, array('menu','title','description','keywords','copyright','themeSelect','subside','themeSelect')))
		$fval = @file_get_contents('files/config/'.$key);
	else
		$fval = @file_get_contents('files/'.$key);
`
And this line
`$file = @fopen('files/password', 'w');`
With
`$file = @fopen('files/config/password', 'w');`
**editText.php**
Replace this line
`$encrypt_pass = @file_get_contents('files/password');`
With
`$encrypt_pass = @file_get_contents('files/config/password');`
And this line
`$file = @fopen("files/$fieldname", "w");`
With
`
if(in_array($fieldname, array('menu','title','description','keywords','copyright','themeSelect','subside','themeSelect')))
	$file = @fopen("files/config/$fieldname", "w");
else
	$file = @fopen("files/$fieldname", "w");
`

Cheers!

**Comment by robiso** [comment]
Pushed a couple of awesome updates, let's see if we can solve this in a more elegant way. WonderCMS wasn't built to work like this.

**Comment by robiso** [comment]
Reopening: I think this is doable with the new version with some extra developing.
It could work with seperated nesting $wCMS->config->pageData and $wCMS->config->everythingElse.

We would need multiple conditions to check between the menu and page meta. If there are any takers on this it's a +1 from me.

**Comment by robiso** [comment]
Closing this for now, if anyone wants to elegantly solve this make a new thread.
