### ISSUE TITLE
What is the use of the addListener function?

### ISSUE THREAD

**Issue by NicolasCARPi** [robiso/wondercms#88]
It is a private function that is not used anywhere else in the code. It can safely be removed imho.

**Comment by robiso** [comment]
It's used for adding listeners with plugins.

Plugin examples that utilize this:
- Summernote plugin: https://github.com/robiso/wondercms-plugins/blob/master/plugins/summernote/summernote.php
- Hits counter plugin: https://github.com/robiso/wondercms-plugins/blob/master/plugins/hits-counter/hits-counter.php

**Comment by NicolasCARPi** [comment]
What is the use of `alerts()`?

Also, if these functions can be used by plugins it would make sense to make them public to signify it can be used "outside".

**Comment by robiso** [comment]
@NicolasCARPi 
> What is the use of `alerts()`?

The `alerts()` function displays all WonderCMS related alerts, such as:
- various warning messages,
- warning for changing default password/login URL,
- alert for showing the "New WonderCMS update" message.

It's primarily used in the theme.php file (of any theme):
https://github.com/robiso/wondercms/blob/master/themes/default/theme.php#L19

Your suggestion will probably be include this in the new release, cheers Nicolas!
