### ISSUE TITLE
More changes

### ISSUE THREAD

**Issue by NicolasCARPi** [robiso/wondercms#89]
So I'm working on the code and trying to make sense out of it.

You require PHP version 7.1 which is great (too many projects are afraid of leaving the 5.x world…).

So I started adding comments for functions and type hinting. This helps A LOT collaborators to figure out what a function does, what are the arguments and how you can use the functions.

You can see the work in progress here:
https://github.com/NicolasCARPi/wondercms/blob/hints/index.php

I didn't do the whole file because it's big and because I wanted to discuss it with you first. Note: this doesn't do anything to the code because there is not (yet) the strict_types enabled. So it's purely decorative (for now). But believe me, it's something you want to have. A single file is already hard to figure out, and without comments or hints it's even harder for new contributors (like me).

This work also allows me to understand better how wondercms works and how it can be improved. It will also allow to detect more bugs with static analyzers.

It's time to start using the cool features of PHP 7.1+ ! ;)

**Comment by NicolasCARPi** [comment]
Another point:

I think having a build step would be great. You will still be able to provide fully cooked zip archives so users can still just unzip and be done with it. But IMHO the source code should not be the final form. Let me explain:

In the function `js()` there is a big chunk of javascript code (with escaped quotes!) that is completely unreadable for humans. Good luck doing anything with this code!

My suggestion:

Have a `wondercms.js` file in human readable form (so with comments and spacing), use a tool like `grunt` to minify the file in `wondercms.min.js` and this is what is read by the function. Same for CSS in the `css()` function.

Docker install would need to be adjusted (not an issue, this is what docker is for). And git install would need steps like (using yarn here but it could be npm):

* yarn install
* yarn build

This change would allow humans to see and modify the CSS and JS of this project. Without this change one would need to copy the code in a beautifier, make a modification, uglify it and put it back… Not really developper friendly.

**Comment by NicolasCARPi** [comment]
You can also see in the PSR2 branch that I added a constant: REPO_URL to avoid repetition all over the code. Note, to further factorize this, because `getExternalFile` is always fetching from the github repo, you could add this to `curl_setopt`: change `$url` in `REPO_URL . $file`. And the argument to the function becomes a file instead of a full URL ;)

Also see how I removed the `$data` variable from the `getOfficialVersion` function. It is useless to store it in memory if it's for returning it immediatly after. Side note: `data` is always a bad name for a variable! (it is not descriptive at all).

**Comment by NicolasCARPi** [comment]
> The only thing I'm hesitant about is extra files (such as wondercms.js), which would partially defeat the purpose of the single page app. Would it help if the js() and css() functions were un-minified in the documentation (probably not as developer friendly as to keeping them unminified in the index.php?

I understand your viewpoint, but see this: aiming for less files is in contradiction with a clean and maintainable project. You want to have everything in one file? Fine. But here the CSS and JS are obfuscated, which is bad. Adding it in the wiki is a bad idea as it means duplicating code and it's really not the place for code anyway. There is a balance to find between having a few files and having maintainable code.

Also, let's say we add a `package.json`, this will allow external services ([or even just github](https://github.blog/2017-11-16-introducing-security-alerts-on-github/)) to scan the libraries you use (like jquery and friends) for vulnerabilities. This improves the security of the app, an argument which I'm sure will touch you ;). Also, this allows text editor to have syntax highlighting and autocompletion, which is a must have (and also it can detect errors in the code depending on how you configured it). So it is imho not a small improvement, but a major and much necessary one.

> Any chance of sending me your PayPal address for a small reward for taking the time to contribute to this project?

No. I have no interest in monetary contribution (but thanks anyway). Let me explain why I'm helping your project. When I started mine, I was very bad at PHP, my code was purely procedural, there was no classes, no interfaces, no custom exceptions, no traits, nothing good. It was a spaghetti mess with code duplicated everywhere. Then I slowly learned all of the above, and got helped by contributors that showed me "a better way to do things". This is what I'm trying to do with your project. Sharing the knowledge I acquired over the years. At first I regarded your project as complete shit by just glancing at the source code (sorry…), then by doing the docker image, I started using it and immediatly found it cute. It felt like it had a soul and for some reason, I started to love it, with all its quirks and defaults. I liked how it was behaving. I liked how it stands out from the rest of the crowd (I mean a database in json, first time I see that!). I liked how you did something out of the ordinary, a completely unorthodox  project. I like this spirit of doing things your way and not looking at what the others do. But this can only go so far, there is a minimum of things to have (like PSR-2). And I decided I wanted to help the project mature and grow. After a while, I found that having a big file with all static functions was no so bad, it's not good for sure, but it's what defines the project, so I accepted it :) Also, contributing to other open source project is enriching both for the contributed project but also for me, as it forces me to be confronted to unknown codebase and maybe learn something along the way.

> Would the new PHP 7.1 functionality break older websites that are still running on PHP 5.5? If so which ones, so we can put up the appropriate warnings to existing users.

Yes definitely. Nothing will work. This is why the next version should maybe be a 3.0.0. With a clear warning that it will not work below 7.1. By doing this, you are doing what devs should do: push users to update their PHP version. There are absolutely no good reasons to try and keep backward compatibility with old PHP. This is how wordpress happens (their codebase is very ugly, hence all the security issues over the years).

**Comment by NicolasCARPi** [comment]
Also, I see you are stuck with jquery version 1.12 (from 2016) when version 3.3 is the latest. Because right now the code is obfuscated, I wasn't able to check if a newer version would work, but it's something that should be done. And this is much easier to do with a proper `package.json` and a build step that minifies the files from the `node_modules` folder and create a bundle of minified code.

**Comment by robiso** [comment]
`I understand your viewpoint, but see this: aiming for less files is in contradiction with a clean and maintainable project. You want to have everything in one file? Fine. But here the CSS and JS are obfuscated, which is bad. Adding it in the wiki is a bad idea as it means duplicating code and it's really not the place for code anyway. There is a balance to find between having a few files and having maintainable code.`
What do you think about the option of having it unminified in the index.php? Let's keep it a *tad* unorthodox. :) 

`Yes definitely. Nothing will work. This is why the next version should maybe be a 3.0.0. With a clear warning that it will not work below 7.1. By doing this, you are doing what devs should do: push users to update their PHP version. There are absolutely no good reasons to try and keep backward compatibility with old PHP. This is how wordpress happens (their codebase is very ugly, hence all the security issues over the years).`
I don't think this is such a big issue at all if it's 3.0.0 and breaks backwards compatibility, would you rather suggest a fork of the CMS or making a new variant? If not, I don't see an issue with releasing a 3.0.0 version. Though I would like to release a version before the 3.0.0 and start warning users beforehand that the new version won't work (if their server is running PHP 7.1 or less).

`Also, I see you are stuck with jquery version 1.12 (from 2016) when version 3.3 is the latest. Because right now the code is obfuscated, I wasn't able to check if a newer version would work, but it's something that should be done. And this is much easier to do with a proper package.json and a build step that minifies the files from the node_modules folder and create a bundle of minified code.`
WonderCMS is persisting with 1.12 as it's [still the most used and cached version of all versions](https://w3techs.com/technologies/details/js-jquery/1/all).
Out of curiosity, checked with the latest jQuery version and it returns this when trying to save something into an editable field.
`TypeError: $.post is not a function`

**Comment by NicolasCARPi** [comment]
> WonderCMS is persisting with 1.12 as it's still the most used and cached version of all versions.

Interesting. The issue I see with that is if a vulnerability is found it will not be fixed by jquery. Also you're missing the improvements made in newer versions. But if you want to stick with it, why not, it's your project after all :)

> TypeError: $.post is not a function

I think it's because you'd need to use the non slim version of jquery. See [SO](https://stackoverflow.com/questions/38793723/uncaught-typeerror-post-is-not-a-function).

> I don't think this is such a big issue at all if it's 3.0.0 and breaks backwards compatibility, would you rather suggest a fork of the CMS or making a new variant?

No just being very clear about the changes, have a clear upgrade path and all should be fine. In a project life, sometimes things need to be broken, otherwise you are stuck with your errors from the past. This is why release notes and major versions exist. So you can break things to improve the software.

> What do you think about the option of having it unminified in the index.php? Let's keep it a tad unorthodox. :)

That would be a good start. But if we want to keep the **fast** requirement in mind, CSS and JS needs to be minified So we can add comments and have aerated code. One way to do it would be to actually commit the minified files. It's not great and it's bad practice, but it would allow to:

* remove the huge obfuscated lines of CSS and JS from the index.php file
* allow a dev to edit the unminified version, minify it with an automatic task, reload the page and see if it worked

This would be I think a good middleground, as you would still serve the minified code, but it would be accessible and readable for humans. And only devs would have to install the minifying tools, fitting with your requirement of "just unzip and it works".

**Comment by NicolasCARPi** [comment]
Note: my text editor (vim) has troubles with syntax highlight around the end of the file because of all those huge JS/CSS/HTML blocks. Also, it's a nightmare to edit anything in there, so this needs to be improved for sure.

![2019-01-20-015808_715x654_scrot](https://user-images.githubusercontent.com/3043706/51433939-e702db00-1c56-11e9-99c7-8cba4a4b440c.png)

I think extracting the JS/CSS is easy. For extracting the HTML one would need to use composer with twig and a cache directory for template caching, so it's a bigger change, but one that would actually make the render much faster (yes, twig really helps with the caching) and the index.php more maintainable. But that's for later I guess. One thing at a time (or two or three at most :p).

**Comment by robiso** [comment]
> Interesting. The issue I see with that is if a vulnerability is found it will not be fixed by jquery. Also you're missing the improvements made in newer versions. But if you want to stick with it, why not, it's your project after all :)
I never saw any other benefit than just loading speed for users websites when using jQuery v1.12.4. Do you have any suggestions that would benefit WonderCMS with the newer version?

> I think it's because you'd need to use the non slim version of jquery. See SO.
You're correct, tried it with just the minified version and it works ok. So if we decided to user a newer version, there's no breaking changes. Would have to test this with a couple of plugins though. :)

> That would be a good start. But if we want to keep the fast requirement in mind, CSS and JS needs to be minified So we can add comments and have aerated code. One way to do it would be to actually commit the minified files. It's not great and it's bad practice, but it would allow to:
I didn't realize this was possible, would love to hear how it can be done.

**Comment by NicolasCARPi** [comment]
> Do you have any suggestions that would benefit WonderCMS with the newer version?

I didn't look at the JS code yet. I'll see if it's worth it.

> I didn't realize using it like that was possible, would love to hear how it can be done?

I'll do a PR for that.

**Comment by robiso** [comment]
@NicolasCARPi, but... do you ever sleep? :)

**Comment by NicolasCARPi** [comment]
I'm on the French timezone. And I'm a night owl yes ;)

**Comment by robiso** [comment]
Well then, bonsoir bien monsieur!
I can't afford to be "night owling" like I used to. We're in the same timezone, cheers from Slovenia!

**Comment by robiso** [comment]
@NicolasCARPi, thank you for taking the time and having the patience with working on this project. I know it must of been hard and challenging for a developer like yourself. :)

The one thing I currently regret is, not being able to reward you in any way other than attribution (woohooo: found a minor way, let's see when it'll be noticed :).

Your jeditable project doesn't have any donations links and serves thousands of happy users, which is absolutely incredible.

I hope, some day, I'll be able to return awesome contributions back at you and that you'll possibly feel half as grateful as I am for you joining in on this project.

Thank you for the kind words, it's an absolute honor hearing it from you!

**Comment by NicolasCARPi** [comment]
> is not being able to reward you in any way other than attribution

Attribution is enough. If you want, you can give money to my employer: https://aider.curie.fr/don/~my-donation?_cv=1 to help cure cancer. Or to these guys: https://www.laquadrature.net/en/.

> Your jeditable project 

This is a project that I maintain but I didn't write it. It was dying and I asked the maintainer to transfer the repo to me. I'm using it in my main PHP project: https://www.elabftw.net so I didn't want to see it die.

**Comment by robiso** [comment]
@NicolasCARPi, donation sent to your employer.

Rest assured you will also be attributed on the news page for all of the coding you're helping out with. In the name of your users, thanks for keeping the project alive!
