### ISSUE TITLE
Nginx configuration in wiki

### ISSUE THREAD

**Issue by NicolasCARPi** [robiso/wondercms#93]
I was setting up a local install of wondercms on my computer, which has an nginx server running.

And I had the error that the page wasn't properly redirecting. Unable to fix the issue, I decided to watch [a movie](https://www.imdb.com/title/tt0138749/) and then realized that it was probably because the software tried to write in the directory (create database on first run), but couldn't because it didn't have the rights. Indeed, `chown -R http:http .` fixed the issue (nginx is running as `http` user).

Of course, this is not the best because now my user can't edit the files (as they are owned by `http`), so I need to allow everyone to edit files. This is why it would be much better to have a separate `data` dir where the webserver has write access to it, but not the rest of the code. Of course, this would prevent the auto update to happen, but that's another issue on its own.

So what I did is revert the own of the files to my user, and make `database.js` and `files` owned by the webserver. It works well this way.

Anyway, the nginx configuration in the wiki is incomplete, here is a complete configuration that should be in the wiki:

~~~nginx
server {
        listen 80;
        # adapt to your server name
        server_name www.wonder-example.com;
        # adapt the path
        root /var/www/wondercms;
        index index.php;
        # prevent directory listing
        autoindex off;

        # rewrite url to make it pretty
        location / {
            if (!-e $request_filename) {
                rewrite ^/(.+)$ /index.php?page=$1 last;
            }
        }

        # prevent access to database.js
        location ~ database.js {
            return 403;
        }

        # use php-fpm for dealing with php files
        location ~ \.php(/|$) {
            # this could also be called fastcgi_params depending on your distribution
            include fastcgi.conf;
            # using unix socket
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
            # uncomment (and comment the one above) if you are using the TCP port 9000 for php-fpm
            # fastcgi_pass 127.0.0.1:9000;
        }
    }
~~~

**Comment by robiso** [comment]
First, thanks for the movie recommendation. :)

If you would suggest and insist on a data folder, that would be acceptable as long as the backup and auto update can be solved. Like you've already said, one thing at a time. :)

Cheers for the updated NGINX config, updated the wiki and credited your solution + added some simple additional instructions.

@NicolasCARPi, closing issue. If you think we should keep it open for further discussion, please let me know.

**Comment by NicolasCARPi** [comment]
You can have syntax highlighting in the wiki. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Use `~~~nginx`

config

`~~~`

**Comment by robiso** [comment]
@NicolasCARPi schooling is in session and you're the teacher! Thanks for sharing your knowledge. :)
Updated the wiki to reflect the schooling session.

**Comment by NicolasCARPi** [comment]
ahah :)

Much prettier now!

I'll see later about security headers we can add to this configuration to match the .htaccess-ultimate.
