### ISSUE TITLE
[Feature implemented in dev branch] Include WYSIWYG editor in default WonderCMS installation

### ISSUE THREAD

**Issue by NicolasCARPi** [robiso/wondercms#95]
wonderCMS is aimed at non technical users from what I understand. But when editing a block, one should know HTML.

My suggestion:

Have a WYSIWYG editor (like TinyMCE or ckEditor) that would hide the html from the user and let the user edit it like if it was in Word/Libreoffice.

Then you could also add a markdown editor so users can choose to edit in markdown.

On the backend, nothing needs to be changed, the text will still be saved as HTML in the database.

But the upside is that users will have a nice editor instead of raw HTML.

Of course this change will add dependencies, but I think the added user friendliness is very worth it.

This is definitely not a priority (some steps need to be taken before adding such functionnalities), but it's something to think about. Let me know what you think about this.

EDIT: I see that [this plugin](https://github.com/nishantmendiratta/wondercms_with_ckeditor) adds ckEditor. I have not tried it but maybe its functionality should be included in the base install. But not like that, as the way it is done in the plugin is improper.

**Comment by robiso** [comment]
@NicolasCARPi, added a cleaned up version of Summernote WYSIWYG to the default WonderCMS installation: https://github.com/robiso/wondercms/tree/dev

**Comment by robiso** [comment]
Closing this issue as it's implemented in the dev branch.
